In [1]:
# Appending Category datasets to usdaHoney3 for ANCOVA/MANCOVA and Stepwise Regressions / ARIMA & VIF

In [11]:
library(dplyr)
library(tidyr)

In [42]:
Cat1 <- read.csv("C:/Users/saslo/Documents/GitHub/FinalProjectEntity/Data/Cat1.csv")
Cat2 <- read.csv("C:/Users/saslo/Data_Science/DS_Portfolio/Queen_Bees/Datasets/Wrangled_Data/cat2.csv")
Cat3 <- read.csv("C:/Users/saslo/Documents/GitHub/FinalProjectEntity/Data/usdaHoney2.csv")
Cat4 <- read.csv("C:/Users/saslo/Data_Science/DS_Portfolio/Queen_Bees/Datasets/Wrangled_Data/usdaNuts_Oils.csv")
Cat5 <- read.csv("C:/Users/saslo/Documents/GitHub/FinalProjectEntity/Data/usdaHoney2.csv")

In [44]:
Cat1
Cat2
Cat3
Cat4
Cat5

    X   Commodity_Description Year Country_Code Attribute_Description
1   45  Dairy, Milk, Fluid    1998 US           Production
2   46  Dairy, Milk, Fluid    1999 US           Production
3   47  Dairy, Milk, Fluid    2000 US           Production
4   48  Dairy, Milk, Fluid    2001 US           Production
5   49  Dairy, Milk, Fluid    2002 US           Production
6   50  Dairy, Milk, Fluid    2003 US           Production
7   51  Dairy, Milk, Fluid    2004 US           Production
8   52  Dairy, Milk, Fluid    2005 US           Production
9   53  Dairy, Milk, Fluid    2006 US           Production
10  54  Dairy, Milk, Fluid    2007 US           Production
11  55  Dairy, Milk, Fluid    2008 US           Production
12  56  Dairy, Milk, Fluid    2009 US           Production
13  57  Dairy, Milk, Fluid    2010 US           Production
14  58  Dairy, Milk, Fluid    2011 US           Production
15  59  Dairy, Milk, Fluid    2012 US           Production
16  75  Honey                 1998 US           Production
17  76  Honey                 1999 US           Production
18  77  Honey                 2000 US           Production
19  78  Honey                 2001 US           Production
20  79  Honey                 2002 US           Production
21  80  Honey                 2003 US           Production
22  81  Honey                 2004 US           Production
23  82  Honey                 2005 US           Production
24  83  Honey                 2006 US           Production
25  84  Honey                 2007 US           Production
26  85  Honey                 2008 US           Production
27  86  Honey                 2009 US           Production
28  87  Honey                 2010 US           Production
29  88  Honey                 2011 US           Production
30  89  Honey                 2012 US           Production
... ... ...                   ...  ...          ...
60  119 Meat, Swine           1998 US           Production
61  120 Meat, Swine           1999 US           Production
62  121 Meat, Swine           2000 US           Production
63  122 Meat, Swine           2001 US           Production
64  123 Meat, Swine           2002 US           Production
65  124 Meat, Swine           2003 US           Production
66  125 Meat, Swine           2004 US           Production
67  126 Meat, Swine           2005 US           Production
68  127 Meat, Swine           2006 US           Production
69  128 Meat, Swine           2007 US           Production
70  129 Meat, Swine           2008 US           Production
71  130 Meat, Swine           2009 US           Production
72  131 Meat, Swine           2010 US           Production
73  132 Meat, Swine           2011 US           Production
74  133 Meat, Swine           2012 US           Production
75  149 Poultry, Meat, Turkey 1998 US           Production
76  150 Poultry, Meat, Turkey 1999 US           Production
77  151 Poultry, Meat, Turkey 2000 US           Production
78  152 Poultry, Meat, Turkey 2001 US           Production
79  153 Poultry, Meat, Turkey 2002 US           Production
80  154 Poultry, Meat, Turkey 2003 US           Production
81  155 Poultry, Meat, Turkey 2004 US           Production
82  156 Poultry, Meat, Turkey 2005 US           Production
83  157 Poultry, Meat, Turkey 2006 US           Production
84  158 Poultry, Meat, Turkey 2007 US           Production
85  159 Poultry, Meat, Turkey 2008 US           Production
86  160 Poultry, Meat, Turkey 2009 US           Production
87  161 Poultry, Meat, Turkey 2010 US           Production
88  162 Poultry, Meat, Turkey 2011 US           Production
89  163 Poultry, Meat, Turkey 2012 US           Production
    Unit_Description Value
1   (MT)             71334000.00
2   (MT)             73750000.00
3   (MT)             75929000.00
4   (MT)             74994000.00
5   (MT)             77140000.00
6   (MT)             77290000.00
7   (MT)             77535000.00
8   (MT)             80286000.00
9   (MT)             82582000.00
10  (MT)             84211000.00
11  (MT)             86410000.00
12  (MT)             86817000.00
13  (MT)             87488000.00
14  (MT)             89020000.00
15  (MT)             91010000.00
16  (MT)                99571.62
17  (MT)                91800.72
18  (MT)                99589.31
19  (MT)                84253.44
20  (MT)                77684.09
21  (MT)                82268.53
22  (MT)                82884.05
23  (MT)                78910.60
24  (MT)                69960.81
25  (MT)                66959.41
26  (MT)                73922.47
27  (MT)                65801.39
28  (MT)                79511.61
29  (MT)                66768.90
30  (MT)                63914.01
... ...              ...
60  (1000 MT CWE)       8623
61  (1000 MT CWE)       8758
62  (1000 MT CWE)       8596
63  (1000 MT CWE)       8691
64  (1000 MT CWE)       8929
65  (1000 MT CWE)       9056
66  (1000 MT CWE)       9313
67  (1000 MT CWE)       9392
68  (1000 MT CWE)       9632
69  (1000 MT CWE)       9962
70  (1000 MT CWE)      10684
71  (1000 MT CWE)      10507
72  (1000 MT CWE)      10187
73  (1000 MT CWE)      10332
74  (1000 MT CWE)      10575
75  (MT)             2365000
76  (MT)             2372000
77  (MT)             2419000
78  (MT)             2490000
79  (MT)             2557000
80  (MT)             2529000
81  (MT)             2441000
82  (MT)             2464000
83  (MT)             2545000
84  (MT)             2667000
85  (MT)             2801000
86  (MT)             2733000
87  (MT)             2607000
88  (MT)             2593000
89  (MT)             2675000

    Commodity_Description Year Country_Code Country_Name  Attribute_Description
1   Apples, Fresh         1998 US           United States Production
2   Apples, Fresh         1999 US           United States Production
3   Apples, Fresh         2000 US           United States Production
4   Apples, Fresh         2001 US           United States Production
5   Apples, Fresh         2002 US           United States Production
6   Apples, Fresh         2003 US           United States Production
7   Apples, Fresh         2004 US           United States Production
8   Apples, Fresh         2005 US           United States Production
9   Apples, Fresh         2006 US           United States Production
10  Apples, Fresh         2007 US           United States Production
11  Apples, Fresh         2008 US           United States Production
12  Apples, Fresh         2009 US           United States Production
13  Apples, Fresh         2010 US           United States Production
14  Apples, Fresh         2011 US           United States Production
15  Apples, Fresh         2012 US           United States Production
16  Asparagus, Fresh      1998 US           United States Production
17  Asparagus, Fresh      1999 US           United States Production
18  Asparagus, Fresh      2000 US           United States Production
19  Asparagus, Fresh      2001 US           United States Production
20  Asparagus, Fresh      2002 US           United States Production
21  Asparagus, Fresh      2003 US           United States Production
22  Asparagus, Fresh      2004 US           United States Production
23  Asparagus, Fresh      2005 US           United States Production
24  Avocados, Fresh       1998 US           United States Production
25  Avocados, Fresh       1999 US           United States Production
26  Avocados, Fresh       2000 US           United States Production
27  Avocados, Fresh       2001 US           United States Production
28  Avocados, Fresh       2002 US           United States Production
29  Avocados, Fresh       2003 US           United States Production
30  Avocados, Fresh       2004 US           United States Production
... ...                   ...  ...          ...           ...
229 Grapefruit, Fresh     1998 US           United States Production
230 Grapefruit, Fresh     1999 US           United States Production
231 Grapefruit, Fresh     2000 US           United States Production
232 Grapefruit, Fresh     2001 US           United States Production
233 Grapefruit, Fresh     2002 US           United States Production
234 Grapefruit, Fresh     2003 US           United States Production
235 Grapefruit, Fresh     2004 US           United States Production
236 Grapefruit, Fresh     2005 US           United States Production
237 Grapefruit, Fresh     2006 US           United States Production
238 Grapefruit, Fresh     2007 US           United States Production
239 Grapefruit, Fresh     2008 US           United States Production
240 Grapefruit, Fresh     2009 US           United States Production
241 Grapefruit, Fresh     2010 US           United States Production
242 Grapefruit, Fresh     2011 US           United States Production
243 Grapefruit, Fresh     2012 US           United States Production
244 Lemons/Limes, Fresh   1998 US           United States Production
245 Lemons/Limes, Fresh   1999 US           United States Production
246 Lemons/Limes, Fresh   2000 US           United States Production
247 Lemons/Limes, Fresh   2001 US           United States Production
248 Lemons/Limes, Fresh   2002 US           United States Production
249 Lemons/Limes, Fresh   2003 US           United States Production
250 Lemons/Limes, Fresh   2004 US           United States Production
251 Lemons/Limes, Fresh   2005 US           United States Production
252 Lemons/Limes, Fresh   2006 US           United States Production
253 Lemons/Limes, Fresh   2007 US           United States Production
254 Lemons/Limes, Fresh   2008 US           United States Production
255 Lemons/Limes, Fresh   2009 US           United States Production
256 Lemons/Limes, Fresh   2010 US           United States Production
257 Lemons/Limes, Fresh   2011 US           United States Production
258 Lemons/Limes, Fresh   2012 US           United States Production
    Unit_Description Value
1   (1000 MT)        5282.724
2   (1000 MT)        5746.060
3   (1000 MT)        5675.890
4   (1000 MT)        5065.060
5   (1000 MT)        4605.810
6   (1000 MT)        4780.600
7   (1000 MT)        5683.040
8   (1000 MT)        5261.960
9   (1000 MT)        5351.610
10  (1000 MT)        4154.195
11  (1000 MT)        4508.344
12  (1000 MT)        4505.000
13  (1000 MT)        4219.541
14  (1000 MT)        4231.474
15  (1000 MT)        4200.000
16  (1000 MT)          65.998
17  (1000 MT)          68.220
18  (1000 MT)          62.233
19  (1000 MT)          84.730
20  (1000 MT)          83.600
21  (1000 MT)          93.530
22  (1000 MT)          81.830
23  (1000 MT)          83.000
24  (1000 MT)         144.469
25  (1000 MT)         166.289
26  (1000 MT)         217.110
27  (1000 MT)         166.289
28  (1000 MT)         180.849
29  (1000 MT)         211.721
30  (1000 MT)         162.722
... ...              ...
229 (1000 MT)        2280
230 (1000 MT)        2507
231 (1000 MT)        2233
232 (1000 MT)        2199
233 (1000 MT)        1872
234 (1000 MT)        1964
235 (1000 MT)         924
236 (1000 MT)        1118
237 (1000 MT)        1476
238 (1000 MT)        1423
239 (1000 MT)        1240
240 (1000 MT)        1123
241 (1000 MT)        1139
242 (1000 MT)        1061
243 (1000 MT)        1092
244 (1000 MT)         678
245 (1000 MT)         762
246 (1000 MT)         904
247 (1000 MT)         727
248 (1000 MT)         931
249 (1000 MT)         724
250 (1000 MT)         789
251 (1000 MT)         889
252 (1000 MT)         724
253 (1000 MT)         638
254 (1000 MT)         862
255 (1000 MT)         800
256 (1000 MT)         853
257 (1000 MT)         771
258 (1000 MT)         827

     X    Commodity_Description     Country_Code Country_Name  Year
1     1   Almonds, Shelled Basis    US           United States 1998
2     2   Almonds, Shelled Basis    US           United States 1999
3     3   Almonds, Shelled Basis    US           United States 2000
4     4   Almonds, Shelled Basis    US           United States 2001
5     5   Almonds, Shelled Basis    US           United States 2002
6     6   Almonds, Shelled Basis    US           United States 2003
7     7   Almonds, Shelled Basis    US           United States 2004
8     8   Almonds, Shelled Basis    US           United States 2005
9     9   Animal Numbers, Cattle    US           United States 1998
10   10   Animal Numbers, Cattle    US           United States 1999
11   11   Animal Numbers, Cattle    US           United States 2000
12   12   Animal Numbers, Cattle    US           United States 2001
13   13   Animal Numbers, Cattle    US           United States 2002
14   14   Animal Numbers, Cattle    US           United States 2003
15   15   Animal Numbers, Cattle    US           United States 2004
16   16   Animal Numbers, Cattle    US           United States 2005
17   17   Animal Numbers, Cattle    US           United States 2006
18   18   Animal Numbers, Swine     US           United States 1998
19   19   Animal Numbers, Swine     US           United States 1999
20   20   Animal Numbers, Swine     US           United States 2000
21   21   Animal Numbers, Swine     US           United States 2001
22   22   Animal Numbers, Swine     US           United States 2002
23   23   Animal Numbers, Swine     US           United States 2003
24   24   Animal Numbers, Swine     US           United States 2004
25   25   Animal Numbers, Swine     US           United States 2005
26   26   Animal Numbers, Swine     US           United States 2006
27   27   Apple Juice, Concentrated US           United States 1998
28   28   Apple Juice, Concentrated US           United States 1999
29   29   Apple Juice, Concentrated US           United States 2000
30   30   Apple Juice, Concentrated US           United States 2001
...  ...  ...                       ...          ...           ...
8284 8284 Oilseed, Peanut           US           United States 2012
8285 8285 Meat, Beef and Veal       US           United States 2012
8286 8286 Meat, Chicken             US           United States 2012
8287 8287 Meat, Swine               US           United States 2012
8288 8288 Walnuts, Inshell Basis    US           United States 2002
8289 8289 Walnuts, Inshell Basis    US           United States 2003
8290 8290 Walnuts, Inshell Basis    US           United States 2004
8291 8291 Walnuts, Inshell Basis    US           United States 2005
8292 8292 Walnuts, Inshell Basis    US           United States 2006
8293 8293 Walnuts, Inshell Basis    US           United States 2007
8294 8294 Walnuts, Inshell Basis    US           United States 2008
8295 8295 Walnuts, Inshell Basis    US           United States 2009
8296 8296 Walnuts, Inshell Basis    US           United States 2010
8297 8297 Walnuts, Inshell Basis    US           United States 2011
8298 8298 Walnuts, Inshell Basis    US           United States 2012
8299 8299 Honey                     US           United States 1998
8300 8300 Honey                     US           United States 1999
8301 8301 Honey                     US           United States 2000
8302 8302 Honey                     US           United States 2001
8303 8303 Honey                     US           United States 2002
8304 8304 Honey                     US           United States 2003
8305 8305 Honey                     US           United States 2004
8306 8306 Honey                     US           United States 2005
8307 8307 Honey                     US           United States 2006
8308 8308 Honey                     US           United States 2007
8309 8309 Honey                     US           United States 2008
8310 8310 Honey                     US           United States 2009
8311 8311 Honey                     US           United States 2010
8312 8312 Honey                     US           United States 2011
8313 8313 Honey                     US           United States 2012
     Attribute_Description Unit_Description Value     Category
1    Production            (MT)             235884    4
2    Production            (MT)             361362    4
3    Production            (MT)             303700    4
4    Production            (MT)             376488    4
5    Production            (MT)             494416    4
6    Production            (MT)             458582    4
7    Production            (MT)             462664    4
8    Production            (MT)             387186    4
9    Production            (1000 HEAD)       38812    1
10   Production            (1000 HEAD)       38796    1
11   Production            (1000 HEAD)       38631    1
12   Production            (1000 HEAD)       38300    1
13   Production            (1000 HEAD)       38224    1
14   Production            (1000 HEAD)       37903    1
15   Production            (1000 HEAD)       37505    1
16   Production            (1000 HEAD)       37780    1
17   Production            (1000 HEAD)       38300    1
18   Production            (1000 HEAD)      105005    1
19   Production            (1000 HEAD)      102352    1
20   Production            (1000 HEAD)      100742    1
21   Production            (1000 HEAD)      100617    1
22   Production            (1000 HEAD)      101677    1
23   Production            (1000 HEAD)      101491    1
24   Production            (1000 HEAD)      102781    1
25   Production            (1000 HEAD)      103685    1
26   Production            (1000 HEAD)      104980    1
27   Production            (MT)             153162    2
28   Production            (MT)             152397    2
29   Production            (MT)             143892    2
30   Production            (MT)             119777    2
...  ...                   ...              ...       ...
8284 Production            (1000 MT)          3064.00 4
8285 Production            (1000 MT CWE)     11845.00 1
8286 Production            (1000 MT)         16856.00 1
8287 Production            (1000 MT CWE)     10554.00 1
8288 Production            (MT)             255800.00 4
8289 Production            (MT)             295700.00 4
8290 Production            (MT)             294800.00 4
8291 Production            (MT)             322100.00 4
8292 Production            (MT)             313900.00 4
8293 Production            (MT)             297600.00 4
8294 Production            (MT)             395533.00 4
8295 Production            (MT)             396440.00 4
8296 Production            (MT)             457221.00 4
8297 Production            (MT)             418212.00 4
8298 Production            (MT)             450871.00 4
8299 Production            MT                99571.62 6
8300 Production            MT                91800.72 6
8301 Production            MT                99589.31 6
8302 Production            MT                84253.44 6
8303 Production            MT                77684.09 6
8304 Production            MT                82268.53 6
8305 Production            MT                82884.05 6
8306 Production            MT                78910.60 6
8307 Production            MT                69960.81 6
8308 Production            MT                66959.41 6
8309 Production            MT                73922.47 6
8310 Production            MT                65801.39 6
8311 Production            MT                79511.61 6
8312 Production            MT                66768.90 6
8313 Production            MT                63914.01 6

    X.1  X    Commodity_Description     Country_Code Country_Name  Year
1    1    602 Walnuts, Inshell Basis    US           United States 1998
2    2    603 Walnuts, Inshell Basis    US           United States 1999
3    3    604 Walnuts, Inshell Basis    US           United States 2000
4    4   6357 Walnuts, Inshell Basis    US           United States 2001
5    5    606 Walnuts, Inshell Basis    US           United States 2002
6    6    607 Walnuts, Inshell Basis    US           United States 2003
7    7    608 Walnuts, Inshell Basis    US           United States 2004
8    8   6361 Walnuts, Inshell Basis    US           United States 2005
9    9   1249 Walnuts, Inshell Basis    US           United States 2006
10  10   6363 Walnuts, Inshell Basis    US           United States 2007
11  11   6364 Walnuts, Inshell Basis    US           United States 2008
12  12   6365 Walnuts, Inshell Basis    US           United States 2009
13  13   4611 Walnuts, Inshell Basis    US           United States 2010
14  14   5479 Walnuts, Inshell Basis    US           United States 2011
15  15   8005 Walnuts, Inshell Basis    US           United States 2012
16  16    477 Pistachios, Inshell Basis US           United States 1998
17  17    478 Pistachios, Inshell Basis US           United States 1999
18  18    479 Pistachios, Inshell Basis US           United States 2000
19  19    480 Pistachios, Inshell Basis US           United States 2001
20  20    481 Pistachios, Inshell Basis US           United States 2002
21  21   2129 Pistachios, Inshell Basis US           United States 2003
22  22   4855 Pistachios, Inshell Basis US           United States 2004
23  23   2612 Pistachios, Inshell Basis US           United States 2005
24  24   7181 Pistachios, Inshell Basis US           United States 2006
25  25   2614 Pistachios, Inshell Basis US           United States 2007
26  26   4859 Pistachios, Inshell Basis US           United States 2008
27  27   4860 Pistachios, Inshell Basis US           United States 2009
28  28   4861 Pistachios, Inshell Basis US           United States 2010
29  29   5702 Pistachios, Inshell Basis US           United States 2011
30  30   7470 Pistachios, Inshell Basis US           United States 2012
... ...  ...  ...                       ...          ...           ...
157  157  320 Oil, Cottonseed           US           United States 1998
158  158  321 Oil, Cottonseed           US           United States 1999
159  159  322 Oil, Cottonseed           US           United States 2000
160  160  323 Oil, Cottonseed           US           United States 2001
161  161  324 Oil, Cottonseed           US           United States 2002
162  162  325 Oil, Cottonseed           US           United States 2003
163  163  326 Oil, Cottonseed           US           United States 2004
164  164  327 Oil, Cottonseed           US           United States 2005
165  165  775 Oil, Cottonseed           US           United States 2006
166  166 1994 Oil, Cottonseed           US           United States 2007
167  167 2210 Oil, Cottonseed           US           United States 2008
168  168 3181 Oil, Cottonseed           US           United States 2009
169  169 7383 Oil, Cottonseed           US           United States 2010
170  170 4989 Oil, Cottonseed           US           United States 2011
171  171 6110 Oil, Cottonseed           US           United States 2012
172 8299 8299 Honey                     US           United States 1998
173 8300 8300 Honey                     US           United States 1999
174 8301 8301 Honey                     US           United States 2000
175 8302 8302 Honey                     US           United States 2001
176 8303 8303 Honey                     US           United States 2002
177 8304 8304 Honey                     US           United States 2003
178 8305 8305 Honey                     US           United States 2004
179 8306 8306 Honey                     US           United States 2005
180 8307 8307 Honey                     US           United States 2006
181 8308 8308 Honey                     US           United States 2007
182 8309 8309 Honey                     US           United States 2008
183 8310 8310 Honey                     US           United States 2009
184 8311 8311 Honey                     US           United States 2010
185 8312 8312 Honey                     US           United States 2011
186 8313 8313 Honey                     US           United States 2012
    Attribute_Description Unit_Description Value     Category
1   Production            (MT)             205931    4
2   Production            (MT)             256734    4
3   Production            (MT)             216816    4
4   Production            (MT)             276700    4
5   Production            (MT)             255825    4
6   Production            (MT)             295741    4
7   Production            (MT)             294834    4
8   Production            (MT)             322100    4
9   Production            (MT)             317515    4
10  Production            (MT)             297600    4
11  Production            (MT)             395500    4
12  Production            (MT)             396400    4
13  Production            (MT)             462660    4
14  Production            (MT)             440000    4
15  Production            (MT)             450871    4
16  Production            (MT)              85275    4
17  Production            (MT)              56056    4
18  Production            (MT)             110179    4
19  Production            (MT)              73240    4
20  Production            (MT)             137562    4
21  Production            (MT)              53970    4
22  Production            (MT)             157400    4
23  Production            (MT)             128400    4
24  Production            (MT)             107955    4
25  Production            (MT)             188694    4
26  Production            (MT)             126100    4
27  Production            (MT)             161025    4
28  Production            (MT)             236775    4
29  Production            (MT)             203150    4
30  Production            (MT)             249929    4
... ...                   ...              ...       ...
157 Production            (MT)             377000.00 4
158 Production            (MT)             426000.00 4
159 Production            (MT)             384000.00 4
160 Production            (MT)             398000.00 4
161 Production            (MT)             329000.00 4
162 Production            (MT)             396000.00 4
163 Production            (MT)             434000.00 4
164 Production            (MT)             435000.00 4
165 Production            (MT)             408000.00 4
166 Production            (MT)             392000.00 4
167 Production            (MT)             386000.00 4
168 Production            (MT)             383000.00 4
169 Production            (MT)             379000.00 4
170 Production            (MT)             379000.00 4
171 Production            (MT)             377000.00 4
172 Production            MT                99571.62 6
173 Production            MT                91800.72 6
174 Production            MT                99589.31 6
175 Production            MT                84253.44 6
176 Production            MT                77684.09 6
177 Production            MT                82268.53 6
178 Production            MT                82884.05 6
179 Production            MT                78910.60 6
180 Production            MT                69960.81 6
181 Production            MT                66959.41 6
182 Production            MT                73922.47 6
183 Production            MT                65801.39 6
184 Production            MT                79511.61 6
185 Production            MT                66768.90 6
186 Production            MT                63914.01 6

     X    Commodity_Description     Country_Code Country_Name  Year
1     1   Almonds, Shelled Basis    US           United States 1998
2     2   Almonds, Shelled Basis    US           United States 1999
3     3   Almonds, Shelled Basis    US           United States 2000
4     4   Almonds, Shelled Basis    US           United States 2001
5     5   Almonds, Shelled Basis    US           United States 2002
6     6   Almonds, Shelled Basis    US           United States 2003
7     7   Almonds, Shelled Basis    US           United States 2004
8     8   Almonds, Shelled Basis    US           United States 2005
9     9   Animal Numbers, Cattle    US           United States 1998
10   10   Animal Numbers, Cattle    US           United States 1999
11   11   Animal Numbers, Cattle    US           United States 2000
12   12   Animal Numbers, Cattle    US           United States 2001
13   13   Animal Numbers, Cattle    US           United States 2002
14   14   Animal Numbers, Cattle    US           United States 2003
15   15   Animal Numbers, Cattle    US           United States 2004
16   16   Animal Numbers, Cattle    US           United States 2005
17   17   Animal Numbers, Cattle    US           United States 2006
18   18   Animal Numbers, Swine     US           United States 1998
19   19   Animal Numbers, Swine     US           United States 1999
20   20   Animal Numbers, Swine     US           United States 2000
21   21   Animal Numbers, Swine     US           United States 2001
22   22   Animal Numbers, Swine     US           United States 2002
23   23   Animal Numbers, Swine     US           United States 2003
24   24   Animal Numbers, Swine     US           United States 2004
25   25   Animal Numbers, Swine     US           United States 2005
26   26   Animal Numbers, Swine     US           United States 2006
27   27   Apple Juice, Concentrated US           United States 1998
28   28   Apple Juice, Concentrated US           United States 1999
29   29   Apple Juice, Concentrated US           United States 2000
30   30   Apple Juice, Concentrated US           United States 2001
...  ...  ...                       ...          ...           ...
8284 8284 Oilseed, Peanut           US           United States 2012
8285 8285 Meat, Beef and Veal       US           United States 2012
8286 8286 Meat, Chicken             US           United States 2012
8287 8287 Meat, Swine               US           United States 2012
8288 8288 Walnuts, Inshell Basis    US           United States 2002
8289 8289 Walnuts, Inshell Basis    US           United States 2003
8290 8290 Walnuts, Inshell Basis    US           United States 2004
8291 8291 Walnuts, Inshell Basis    US           United States 2005
8292 8292 Walnuts, Inshell Basis    US           United States 2006
8293 8293 Walnuts, Inshell Basis    US           United States 2007
8294 8294 Walnuts, Inshell Basis    US           United States 2008
8295 8295 Walnuts, Inshell Basis    US           United States 2009
8296 8296 Walnuts, Inshell Basis    US           United States 2010
8297 8297 Walnuts, Inshell Basis    US           United States 2011
8298 8298 Walnuts, Inshell Basis    US           United States 2012
8299 8299 Honey                     US           United States 1998
8300 8300 Honey                     US           United States 1999
8301 8301 Honey                     US           United States 2000
8302 8302 Honey                     US           United States 2001
8303 8303 Honey                     US           United States 2002
8304 8304 Honey                     US           United States 2003
8305 8305 Honey                     US           United States 2004
8306 8306 Honey                     US           United States 2005
8307 8307 Honey                     US           United States 2006
8308 8308 Honey                     US           United States 2007
8309 8309 Honey                     US           United States 2008
8310 8310 Honey                     US           United States 2009
8311 8311 Honey                     US           United States 2010
8312 8312 Honey                     US           United States 2011
8313 8313 Honey                     US           United States 2012
     Attribute_Description Unit_Description Value     Category
1    Production            (MT)             235884    4
2    Production            (MT)             361362    4
3    Production            (MT)             303700    4
4    Production            (MT)             376488    4
5    Production            (MT)             494416    4
6    Production            (MT)             458582    4
7    Production            (MT)             462664    4
8    Production            (MT)             387186    4
9    Production            (1000 HEAD)       38812    1
10   Production            (1000 HEAD)       38796    1
11   Production            (1000 HEAD)       38631    1
12   Production            (1000 HEAD)       38300    1
13   Production            (1000 HEAD)       38224    1
14   Production            (1000 HEAD)       37903    1
15   Production            (1000 HEAD)       37505    1
16   Production            (1000 HEAD)       37780    1
17   Production            (1000 HEAD)       38300    1
18   Production            (1000 HEAD)      105005    1
19   Production            (1000 HEAD)      102352    1
20   Production            (1000 HEAD)      100742    1
21   Production            (1000 HEAD)      100617    1
22   Production            (1000 HEAD)      101677    1
23   Production            (1000 HEAD)      101491    1
24   Production            (1000 HEAD)      102781    1
25   Production            (1000 HEAD)      103685    1
26   Production            (1000 HEAD)      104980    1
27   Production            (MT)             153162    2
28   Production            (MT)             152397    2
29   Production            (MT)             143892    2
30   Production            (MT)             119777    2
...  ...                   ...              ...       ...
8284 Production            (1000 MT)          3064.00 4
8285 Production            (1000 MT CWE)     11845.00 1
8286 Production            (1000 MT)         16856.00 1
8287 Production            (1000 MT CWE)     10554.00 1
8288 Production            (MT)             255800.00 4
8289 Production            (MT)             295700.00 4
8290 Production            (MT)             294800.00 4
8291 Production            (MT)             322100.00 4
8292 Production            (MT)             313900.00 4
8293 Production            (MT)             297600.00 4
8294 Production            (MT)             395533.00 4
8295 Production            (MT)             396440.00 4
8296 Production            (MT)             457221.00 4
8297 Production            (MT)             418212.00 4
8298 Production            (MT)             450871.00 4
8299 Production            MT                99571.62 6
8300 Production            MT                91800.72 6
8301 Production            MT                99589.31 6
8302 Production            MT                84253.44 6
8303 Production            MT                77684.09 6
8304 Production            MT                82268.53 6
8305 Production            MT                82884.05 6
8306 Production            MT                78910.60 6
8307 Production            MT                69960.81 6
8308 Production            MT                66959.41 6
8309 Production            MT                73922.47 6
8310 Production            MT                65801.39 6
8311 Production            MT                79511.61 6
8312 Production            MT                66768.90 6
8313 Production            MT                63914.01 6

In [43]:
# Checking Cat 1 Measurements
unique(Cat1$Unit_Description)

[1] "(MT)"          "(1000 MT CWE)"

In [45]:
# Separating data for conversion
Cat1CWE <- filter(Cat1, Unit_Description == '(1000 MT CWE)');
Cat1CWE

   X   Commodity_Description Year Country_Code Attribute_Description
1   90 Meat, Beef and Veal   1998 US           Production
2   91 Meat, Beef and Veal   1999 US           Production
3   92 Meat, Beef and Veal   2000 US           Production
4   93 Meat, Beef and Veal   2001 US           Production
5   94 Meat, Beef and Veal   2002 US           Production
6   95 Meat, Beef and Veal   2003 US           Production
7   96 Meat, Beef and Veal   2004 US           Production
8   97 Meat, Beef and Veal   2005 US           Production
9   98 Meat, Beef and Veal   2006 US           Production
10  99 Meat, Beef and Veal   2007 US           Production
11 100 Meat, Beef and Veal   2008 US           Production
12 101 Meat, Beef and Veal   2009 US           Production
13 102 Meat, Beef and Veal   2010 US           Production
14 103 Meat, Beef and Veal   2011 US           Production
15 104 Meat, Beef and Veal   2012 US           Production
16 119 Meat, Swine           1998 US           Production
17 120 Meat, Swine           1999 US           Production
18 121 Meat, Swine           2000 US           Production
19 122 Meat, Swine           2001 US           Production
20 123 Meat, Swine           2002 US           Production
21 124 Meat, Swine           2003 US           Production
22 125 Meat, Swine           2004 US           Production
23 126 Meat, Swine           2005 US           Production
24 127 Meat, Swine           2006 US           Production
25 128 Meat, Swine           2007 US           Production
26 129 Meat, Swine           2008 US           Production
27 130 Meat, Swine           2009 US           Production
28 131 Meat, Swine           2010 US           Production
29 132 Meat, Swine           2011 US           Production
30 133 Meat, Swine           2012 US           Production
   Unit_Description Value
1  (1000 MT CWE)    11804
2  (1000 MT CWE)    12124
3  (1000 MT CWE)    12298
4  (1000 MT CWE)    11983
5  (1000 MT CWE)    12427
6  (1000 MT CWE)    12039
7  (1000 MT CWE)    11261
8  (1000 MT CWE)    11318
9  (1000 MT CWE)    11981
10 (1000 MT CWE)    12168
11 (1000 MT CWE)    12226
12 (1000 MT CWE)    12203
13 (1000 MT CWE)    12048
14 (1000 MT CWE)    12048
15 (1000 MT CWE)    11855
16 (1000 MT CWE)     8623
17 (1000 MT CWE)     8758
18 (1000 MT CWE)     8596
19 (1000 MT CWE)     8691
20 (1000 MT CWE)     8929
21 (1000 MT CWE)     9056
22 (1000 MT CWE)     9313
23 (1000 MT CWE)     9392
24 (1000 MT CWE)     9632
25 (1000 MT CWE)     9962
26 (1000 MT CWE)    10684
27 (1000 MT CWE)    10507
28 (1000 MT CWE)    10187
29 (1000 MT CWE)    10332
30 (1000 MT CWE)    10575

In [46]:
# Converting & recoding columns
Cat1CWE <- mutate(Cat1CWE, Value = Value * 1000)
CWE <- mutate(Cat1CWE, Unit_Description = "MT")
CWE

   X   Commodity_Description Year Country_Code Attribute_Description
1   90 Meat, Beef and Veal   1998 US           Production
2   91 Meat, Beef and Veal   1999 US           Production
3   92 Meat, Beef and Veal   2000 US           Production
4   93 Meat, Beef and Veal   2001 US           Production
5   94 Meat, Beef and Veal   2002 US           Production
6   95 Meat, Beef and Veal   2003 US           Production
7   96 Meat, Beef and Veal   2004 US           Production
8   97 Meat, Beef and Veal   2005 US           Production
9   98 Meat, Beef and Veal   2006 US           Production
10  99 Meat, Beef and Veal   2007 US           Production
11 100 Meat, Beef and Veal   2008 US           Production
12 101 Meat, Beef and Veal   2009 US           Production
13 102 Meat, Beef and Veal   2010 US           Production
14 103 Meat, Beef and Veal   2011 US           Production
15 104 Meat, Beef and Veal   2012 US           Production
16 119 Meat, Swine           1998 US           Production
17 120 Meat, Swine           1999 US           Production
18 121 Meat, Swine           2000 US           Production
19 122 Meat, Swine           2001 US           Production
20 123 Meat, Swine           2002 US           Production
21 124 Meat, Swine           2003 US           Production
22 125 Meat, Swine           2004 US           Production
23 126 Meat, Swine           2005 US           Production
24 127 Meat, Swine           2006 US           Production
25 128 Meat, Swine           2007 US           Production
26 129 Meat, Swine           2008 US           Production
27 130 Meat, Swine           2009 US           Production
28 131 Meat, Swine           2010 US           Production
29 132 Meat, Swine           2011 US           Production
30 133 Meat, Swine           2012 US           Production
   Unit_Description Value
1  MT               11804000
2  MT               12124000
3  MT               12298000
4  MT               11983000
5  MT               12427000
6  MT               12039000
7  MT               11261000
8  MT               11318000
9  MT               11981000
10 MT               12168000
11 MT               12226000
12 MT               12203000
13 MT               12048000
14 MT               12048000
15 MT               11855000
16 MT                8623000
17 MT                8758000
18 MT                8596000
19 MT                8691000
20 MT                8929000
21 MT                9056000
22 MT                9313000
23 MT                9392000
24 MT                9632000
25 MT                9962000
26 MT               10684000
27 MT               10507000
28 MT               10187000
29 MT               10332000
30 MT               10575000

In [24]:
# Dropping previous CWE data
Cat1 <- subset(Cat1, Unit_Description != '(1000 MT CWE)');

In [25]:
# Appending converted CWE Measurements to Cat1 df
Cat1 <- rbind(Cat1, CWE);
Cat1

    X   Commodity_Description Year Country_Code Attribute_Description
1   45  Dairy, Milk, Fluid    1998 US           Production
2   46  Dairy, Milk, Fluid    1999 US           Production
3   47  Dairy, Milk, Fluid    2000 US           Production
4   48  Dairy, Milk, Fluid    2001 US           Production
5   49  Dairy, Milk, Fluid    2002 US           Production
6   50  Dairy, Milk, Fluid    2003 US           Production
7   51  Dairy, Milk, Fluid    2004 US           Production
8   52  Dairy, Milk, Fluid    2005 US           Production
9   53  Dairy, Milk, Fluid    2006 US           Production
10  54  Dairy, Milk, Fluid    2007 US           Production
11  55  Dairy, Milk, Fluid    2008 US           Production
12  56  Dairy, Milk, Fluid    2009 US           Production
13  57  Dairy, Milk, Fluid    2010 US           Production
14  58  Dairy, Milk, Fluid    2011 US           Production
15  59  Dairy, Milk, Fluid    2012 US           Production
16  75  Honey                 1998 US           Production
17  76  Honey                 1999 US           Production
18  77  Honey                 2000 US           Production
19  78  Honey                 2001 US           Production
20  79  Honey                 2002 US           Production
21  80  Honey                 2003 US           Production
22  81  Honey                 2004 US           Production
23  82  Honey                 2005 US           Production
24  83  Honey                 2006 US           Production
25  84  Honey                 2007 US           Production
26  85  Honey                 2008 US           Production
27  86  Honey                 2009 US           Production
28  87  Honey                 2010 US           Production
29  88  Honey                 2011 US           Production
30  89  Honey                 2012 US           Production
... ... ...                   ...  ...          ...
112  90 Meat, Beef and Veal   1998 US           Production
212  91 Meat, Beef and Veal   1999 US           Production
32   92 Meat, Beef and Veal   2000 US           Production
42   93 Meat, Beef and Veal   2001 US           Production
511  94 Meat, Beef and Veal   2002 US           Production
62   95 Meat, Beef and Veal   2003 US           Production
72   96 Meat, Beef and Veal   2004 US           Production
811  97 Meat, Beef and Veal   2005 US           Production
92   98 Meat, Beef and Veal   2006 US           Production
102  99 Meat, Beef and Veal   2007 US           Production
113 100 Meat, Beef and Veal   2008 US           Production
122 101 Meat, Beef and Veal   2009 US           Production
132 102 Meat, Beef and Veal   2010 US           Production
142 103 Meat, Beef and Veal   2011 US           Production
152 104 Meat, Beef and Veal   2012 US           Production
162 119 Meat, Swine           1998 US           Production
172 120 Meat, Swine           1999 US           Production
182 121 Meat, Swine           2000 US           Production
192 122 Meat, Swine           2001 US           Production
202 123 Meat, Swine           2002 US           Production
213 124 Meat, Swine           2003 US           Production
222 125 Meat, Swine           2004 US           Production
232 126 Meat, Swine           2005 US           Production
242 127 Meat, Swine           2006 US           Production
252 128 Meat, Swine           2007 US           Production
262 129 Meat, Swine           2008 US           Production
272 130 Meat, Swine           2009 US           Production
282 131 Meat, Swine           2010 US           Production
292 132 Meat, Swine           2011 US           Production
302 133 Meat, Swine           2012 US           Production
    Unit_Description Value
1   (MT)             71334000.00
2   (MT)             73750000.00
3   (MT)             75929000.00
4   (MT)             74994000.00
5   (MT)             77140000.00
6   (MT)             77290000.00
7   (MT)             77535000.00
8   (MT)             80286000.00
9   (MT)             82582000.00
10  (MT)             84211000.00
11  (MT)             86410000.00
12  (MT)             86817000.00
13  (MT)             87488000.00
14  (MT)             89020000.00
15  (MT)             91010000.00
16  (MT)                99571.62
17  (MT)                91800.72
18  (MT)                99589.31
19  (MT)                84253.44
20  (MT)                77684.09
21  (MT)                82268.53
22  (MT)                82884.05
23  (MT)                78910.60
24  (MT)                69960.81
25  (MT)                66959.41
26  (MT)                73922.47
27  (MT)                65801.39
28  (MT)                79511.61
29  (MT)                66768.90
30  (MT)                63914.01
... ...              ...
112 MT               11804000
212 MT               12124000
32  MT               12298000
42  MT               11983000
511 MT               12427000
62  MT               12039000
72  MT               11261000
811 MT               11318000
92  MT               11981000
102 MT               12168000
113 MT               12226000
122 MT               12203000
132 MT               12048000
142 MT               12048000
152 MT               11855000
162 MT                8623000
172 MT                8758000
182 MT                8596000
192 MT                8691000
202 MT                8929000
213 MT                9056000
222 MT                9313000
232 MT                9392000
242 MT                9632000
252 MT                9962000
262 MT               10684000
272 MT               10507000
282 MT               10187000
292 MT               10332000
302 MT               10575000

In [47]:
# Converting Cat2 value from (1000 MT) to (MT)
newmt <- mutate(Cat2, Value = Value * 1000)
newDESC <- mutate(newmt, Unit_Description = "MT")
Cat2 <- newDESC
Cat2

    Commodity_Description Year Country_Code Country_Name  Attribute_Description
1   Apples, Fresh         1998 US           United States Production
2   Apples, Fresh         1999 US           United States Production
3   Apples, Fresh         2000 US           United States Production
4   Apples, Fresh         2001 US           United States Production
5   Apples, Fresh         2002 US           United States Production
6   Apples, Fresh         2003 US           United States Production
7   Apples, Fresh         2004 US           United States Production
8   Apples, Fresh         2005 US           United States Production
9   Apples, Fresh         2006 US           United States Production
10  Apples, Fresh         2007 US           United States Production
11  Apples, Fresh         2008 US           United States Production
12  Apples, Fresh         2009 US           United States Production
13  Apples, Fresh         2010 US           United States Production
14  Apples, Fresh         2011 US           United States Production
15  Apples, Fresh         2012 US           United States Production
16  Asparagus, Fresh      1998 US           United States Production
17  Asparagus, Fresh      1999 US           United States Production
18  Asparagus, Fresh      2000 US           United States Production
19  Asparagus, Fresh      2001 US           United States Production
20  Asparagus, Fresh      2002 US           United States Production
21  Asparagus, Fresh      2003 US           United States Production
22  Asparagus, Fresh      2004 US           United States Production
23  Asparagus, Fresh      2005 US           United States Production
24  Avocados, Fresh       1998 US           United States Production
25  Avocados, Fresh       1999 US           United States Production
26  Avocados, Fresh       2000 US           United States Production
27  Avocados, Fresh       2001 US           United States Production
28  Avocados, Fresh       2002 US           United States Production
29  Avocados, Fresh       2003 US           United States Production
30  Avocados, Fresh       2004 US           United States Production
... ...                   ...  ...          ...           ...
229 Grapefruit, Fresh     1998 US           United States Production
230 Grapefruit, Fresh     1999 US           United States Production
231 Grapefruit, Fresh     2000 US           United States Production
232 Grapefruit, Fresh     2001 US           United States Production
233 Grapefruit, Fresh     2002 US           United States Production
234 Grapefruit, Fresh     2003 US           United States Production
235 Grapefruit, Fresh     2004 US           United States Production
236 Grapefruit, Fresh     2005 US           United States Production
237 Grapefruit, Fresh     2006 US           United States Production
238 Grapefruit, Fresh     2007 US           United States Production
239 Grapefruit, Fresh     2008 US           United States Production
240 Grapefruit, Fresh     2009 US           United States Production
241 Grapefruit, Fresh     2010 US           United States Production
242 Grapefruit, Fresh     2011 US           United States Production
243 Grapefruit, Fresh     2012 US           United States Production
244 Lemons/Limes, Fresh   1998 US           United States Production
245 Lemons/Limes, Fresh   1999 US           United States Production
246 Lemons/Limes, Fresh   2000 US           United States Production
247 Lemons/Limes, Fresh   2001 US           United States Production
248 Lemons/Limes, Fresh   2002 US           United States Production
249 Lemons/Limes, Fresh   2003 US           United States Production
250 Lemons/Limes, Fresh   2004 US           United States Production
251 Lemons/Limes, Fresh   2005 US           United States Production
252 Lemons/Limes, Fresh   2006 US           United States Production
253 Lemons/Limes, Fresh   2007 US           United States Production
254 Lemons/Limes, Fresh   2008 US           United States Production
255 Lemons/Limes, Fresh   2009 US           United States Production
256 Lemons/Limes, Fresh   2010 US           United States Production
257 Lemons/Limes, Fresh   2011 US           United States Production
258 Lemons/Limes, Fresh   2012 US           United States Production
    Unit_Description Value
1   MT               5282724
2   MT               5746060
3   MT               5675890
4   MT               5065060
5   MT               4605810
6   MT               4780600
7   MT               5683040
8   MT               5261960
9   MT               5351610
10  MT               4154195
11  MT               4508344
12  MT               4505000
13  MT               4219541
14  MT               4231474
15  MT               4200000
16  MT                 65998
17  MT                 68220
18  MT                 62233
19  MT                 84730
20  MT                 83600
21  MT                 93530
22  MT                 81830
23  MT                 83000
24  MT                144469
25  MT                166289
26  MT                217110
27  MT                166289
28  MT                180849
29  MT                211721
30  MT                162722
... ...              ...
229 MT               2280000
230 MT               2507000
231 MT               2233000
232 MT               2199000
233 MT               1872000
234 MT               1964000
235 MT                924000
236 MT               1118000
237 MT               1476000
238 MT               1423000
239 MT               1240000
240 MT               1123000
241 MT               1139000
242 MT               1061000
243 MT               1092000
244 MT                678000
245 MT                762000
246 MT                904000
247 MT                727000
248 MT                931000
249 MT                724000
250 MT                789000
251 MT                889000
252 MT                724000
253 MT                638000
254 MT                862000
255 MT                800000
256 MT                853000
257 MT                771000
258 MT                827000

In [29]:
# Wrangling Cat 3

            [,1]        [,2]       [,3]       [,4]       [,5]
Year            1998.00    1999.00    2000.00    2001.00    2002.00
CoffeeValue    13920.00    9780.00   11100.00   10980.00 1303740.00
HoneyValue     99571.62   91800.72   99589.31   84253.44   77684.09
CottonValue  3006720.00 2112480.00 2397600.00 2371680.00 2112480.00
SugarValue  20431000.00 7276000.00 7597000.00  183000.00  163000.00
            [,6]         [,7]         [,8]         [,9]         [,10]
Year        2.003000e+03 2.004000e+03       2005.0 2.006000e+03 2.007000e+03
CoffeeValue 1.032540e+09 1.095300e+09 1395060000.0 1.433400e+09 4.365600e+08
HoneyValue  8.226853e+04 8.288405e+04      78910.6 6.996081e+04 6.695941e+04
CottonValue 2.112480e+06 2.410560e+06 3665088000.0 3.712608e+09 4.385448e+09
SugarValue  5.800000e+08 1.860000e+05   13918000.0 2.030300e+07 2.325100e+07
            [,11]        [,12]        [,13]        [,14]        [,15]
Year        2.008000e+03 2.009000e+03 2.010000e+03 2.011000e+03 2.012000e+03
CoffeeValue 4.558200e+08 4.921800e+08 8.350800e+08 4.300200e+08 1.218180e+09
HoneyValue  7.392247e+04 6.580139e+04 7.951161e+04 6.676890e+04 6.391401e+04
CottonValue 5.160240e+09 5.022216e+09 1.468800e+11 2.199053e+11 2.227565e+11
SugarValue  6.800000e+08 6.066000e+08 6.041310e+08 5.277200e+08 2.389000e+07

In [28]:
# Subsetting category dfs to only keep necessary columns
Cat1 <- subset(Cat1, select = c('Commodity_Description', 'Year', 'Value'))
Cat2 <- subset(Cat2, select = c('Commodity_Description', 'Year', 'Value'))
Cat4 <- subset(Cat4, select = c('Commodity_Description', 'Year', 'Value'))

In [41]:
# Appending Category dfs to eachother
CommodUS98_12 <- rbind(Cat1, Cat2, Cat4)
CommodUS98_12

     Commodity_Description Year Value
1    Dairy, Milk, Fluid    1998 71334000.00
2    Dairy, Milk, Fluid    1999 73750000.00
3    Dairy, Milk, Fluid    2000 75929000.00
4    Dairy, Milk, Fluid    2001 74994000.00
5    Dairy, Milk, Fluid    2002 77140000.00
6    Dairy, Milk, Fluid    2003 77290000.00
7    Dairy, Milk, Fluid    2004 77535000.00
8    Dairy, Milk, Fluid    2005 80286000.00
9    Dairy, Milk, Fluid    2006 82582000.00
10   Dairy, Milk, Fluid    2007 84211000.00
11   Dairy, Milk, Fluid    2008 86410000.00
12   Dairy, Milk, Fluid    2009 86817000.00
13   Dairy, Milk, Fluid    2010 87488000.00
14   Dairy, Milk, Fluid    2011 89020000.00
15   Dairy, Milk, Fluid    2012 91010000.00
16   Honey                 1998    99571.62
17   Honey                 1999    91800.72
18   Honey                 2000    99589.31
19   Honey                 2001    84253.44
20   Honey                 2002    77684.09
21   Honey                 2003    82268.53
22   Honey                 2004    82884.05
23   Honey                 2005    78910.60
24   Honey                 2006    69960.81
25   Honey                 2007    66959.41
26   Honey                 2008    73922.47
27   Honey                 2009    65801.39
28   Honey                 2010    79511.61
29   Honey                 2011    66768.90
30   Honey                 2012    63914.01
...  ...                   ...  ...
1571 Oil, Cottonseed       1998 377000.00
1581 Oil, Cottonseed       1999 426000.00
1591 Oil, Cottonseed       2000 384000.00
1601 Oil, Cottonseed       2001 398000.00
1613 Oil, Cottonseed       2002 329000.00
1622 Oil, Cottonseed       2003 396000.00
1631 Oil, Cottonseed       2004 434000.00
1641 Oil, Cottonseed       2005 435000.00
1651 Oil, Cottonseed       2006 408000.00
1661 Oil, Cottonseed       2007 392000.00
1671 Oil, Cottonseed       2008 386000.00
1681 Oil, Cottonseed       2009 383000.00
1691 Oil, Cottonseed       2010 379000.00
1701 Oil, Cottonseed       2011 379000.00
1713 Oil, Cottonseed       2012 377000.00
1722 Honey                 1998  99571.62
1731 Honey                 1999  91800.72
1741 Honey                 2000  99589.31
1751 Honey                 2001  84253.44
1761 Honey                 2002  77684.09
1771 Honey                 2003  82268.53
1781 Honey                 2004  82884.05
1791 Honey                 2005  78910.60
1801 Honey                 2006  69960.81
1813 Honey                 2007  66959.41
1822 Honey                 2008  73922.47
1831 Honey                 2009  65801.39
1841 Honey                 2010  79511.61
1851 Honey                 2011  66768.90
1861 Honey                 2012  63914.01

In [49]:
# Dropping multiple honey values
ComUS98_12 = aggregate(CommodUS98_12$Value, by=list(CommodUS98_12$Commodity_Description,CommodUS98_12$Year), FUN=max)
ComUS98_12

    Group.1                     Group.2 x
1   Almonds, Shelled Basis      1998       235884.00
2   Apples, Fresh               1998      5282724.00
3   Asparagus, Fresh            1998        65998.00
4   Avocados, Fresh             1998       144469.00
5   Corn                        1998    247882000.00
6   Dairy, Milk, Fluid          1998     71334000.00
7   Filberts, Inshell Basis     1998        14061.00
8   Fresh Apricots              1998       107492.00
9   Fresh Cherries,(Sweet&Sour) 1998       336521.00
10  Fresh Peaches & Nectarines  1998      1248377.00
11  Fresh Plums & Prunes        1998       486796.00
12  Grapefruit, Fresh           1998      2280000.00
13  Grapes, Fresh               1998       708325.00
14  Honey                       1998        99571.62
15  Kiwifruit                   1998        31389.00
16  Lemons/Limes, Fresh         1998       678000.00
17  Macadamia, Inshell Basis    1998        26082.00
18  Meat, Beef and Veal         1998     11804000.00
19  Meat, Swine                 1998      8623000.00
20  Oil, Cottonseed             1998       377000.00
21  Oil, Olive                  1998         1000.00
22  Oil, Peanut                 1998        66000.00
23  Oil, Rapeseed               1998       290000.00
24  Oil, Soybean                1998      8202000.00
25  Oil, Sunflowerseed          1998       534000.00
26  Orange Juice                1998       879226.00
27  Oranges, Fresh              1998      8989000.00
28  Pears, Fresh                1998       880061.00
29  Pecans, Inshell Basis       1998        66467.00
30  Pistachios, Inshell Basis   1998        85275.00
... ...                         ...     ...
474 Tangerines/Mandarins, Fresh 2011       635000.00
475 Walnuts, Inshell Basis      2011       440000.00
476 Almonds, Shelled Basis      2012       952500.00
477 Apples, Fresh               2012      4200000.00
478 Corn                        2012    375683000.00
479 Dairy, Milk, Fluid          2012     91010000.00
480 Filberts, Inshell Basis     2012        36300.00
481 Fresh Cherries,(Sweet&Sour) 2012       418135.00
482 Fresh Peaches & Nectarines  2012      1099300.00
483 Grapefruit, Fresh           2012      1092000.00
484 Grapes, Fresh               2012       908000.00
485 Honey                       2012        63914.01
486 Lemons/Limes, Fresh         2012       827000.00
487 Meat, Beef and Veal         2012     11855000.00
488 Meat, Chicken               2012     16856000.00
489 Meat, Swine                 2012     10575000.00
490 Oil, Cottonseed             2012       377000.00
491 Oil, Olive                  2012        10000.00
492 Oil, Peanut                 2012       108000.00
493 Oil, Rapeseed               2012       626000.00
494 Oil, Soybean                2012      8990000.00
495 Oil, Sunflowerseed          2012       248000.00
496 Orange Juice                2012       662719.00
497 Oranges, Fresh              2012      8014000.00
498 Pears, Fresh                2012       796338.00
499 Pistachios, Inshell Basis   2012       249929.00
500 Poultry, Meat, Turkey       2012      2675000.00
501 Raisins                     2012       313795.00
502 Tangerines/Mandarins, Fresh 2012       664000.00
503 Walnuts, Inshell Basis      2012       450871.00

In [61]:
# Renaming Columns
ComUS98_12 <- rename(ComUS98_12, Commodity = Group.1)
ComUS98_12 <- rename(ComUS98_12, Year = Group.2)
ComUS98_12 <- rename(ComUS98_12, Metric.Tons = x)

ERROR: Error in `stop_subscript()`:
! Can't rename columns that don't exist.
x Column `Group.1` doesn't exist.

In [60]:
# Renaming Dataframe
USprod98_12 <- ComUS98_12
USprod98_12

    Commodity                   Year Metric.Tons
1   Almonds, Shelled Basis      1998    235884.00
2   Apples, Fresh               1998   5282724.00
3   Asparagus, Fresh            1998     65998.00
4   Avocados, Fresh             1998    144469.00
5   Corn                        1998 247882000.00
6   Dairy, Milk, Fluid          1998  71334000.00
7   Filberts, Inshell Basis     1998     14061.00
8   Fresh Apricots              1998    107492.00
9   Fresh Cherries,(Sweet&Sour) 1998    336521.00
10  Fresh Peaches & Nectarines  1998   1248377.00
11  Fresh Plums & Prunes        1998    486796.00
12  Grapefruit, Fresh           1998   2280000.00
13  Grapes, Fresh               1998    708325.00
14  Honey                       1998     99571.62
15  Kiwifruit                   1998     31389.00
16  Lemons/Limes, Fresh         1998    678000.00
17  Macadamia, Inshell Basis    1998     26082.00
18  Meat, Beef and Veal         1998  11804000.00
19  Meat, Swine                 1998   8623000.00
20  Oil, Cottonseed             1998    377000.00
21  Oil, Olive                  1998      1000.00
22  Oil, Peanut                 1998     66000.00
23  Oil, Rapeseed               1998    290000.00
24  Oil, Soybean                1998   8202000.00
25  Oil, Sunflowerseed          1998    534000.00
26  Orange Juice                1998    879226.00
27  Oranges, Fresh              1998   8989000.00
28  Pears, Fresh                1998    880061.00
29  Pecans, Inshell Basis       1998     66467.00
30  Pistachios, Inshell Basis   1998     85275.00
... ...                         ...  ...
474 Tangerines/Mandarins, Fresh 2011    635000.00
475 Walnuts, Inshell Basis      2011    440000.00
476 Almonds, Shelled Basis      2012    952500.00
477 Apples, Fresh               2012   4200000.00
478 Corn                        2012 375683000.00
479 Dairy, Milk, Fluid          2012  91010000.00
480 Filberts, Inshell Basis     2012     36300.00
481 Fresh Cherries,(Sweet&Sour) 2012    418135.00
482 Fresh Peaches & Nectarines  2012   1099300.00
483 Grapefruit, Fresh           2012   1092000.00
484 Grapes, Fresh               2012    908000.00
485 Honey                       2012     63914.01
486 Lemons/Limes, Fresh         2012    827000.00
487 Meat, Beef and Veal         2012  11855000.00
488 Meat, Chicken               2012  16856000.00
489 Meat, Swine                 2012  10575000.00
490 Oil, Cottonseed             2012    377000.00
491 Oil, Olive                  2012     10000.00
492 Oil, Peanut                 2012    108000.00
493 Oil, Rapeseed               2012    626000.00
494 Oil, Soybean                2012   8990000.00
495 Oil, Sunflowerseed          2012    248000.00
496 Orange Juice                2012    662719.00
497 Oranges, Fresh              2012   8014000.00
498 Pears, Fresh                2012    796338.00
499 Pistachios, Inshell Basis   2012    249929.00
500 Poultry, Meat, Turkey       2012   2675000.00
501 Raisins                     2012    313795.00
502 Tangerines/Mandarins, Fresh 2012    664000.00
503 Walnuts, Inshell Basis      2012    450871.00