# Wrangling dataframe for 1998 and 2021 Export / Import / Domestic Consumption / Production comparisons Worldwide

In [61]:
# Load Packages
library(readr)
library(dplyr)

In [2]:
# Loading in dataframe
USDA <- read.csv("../Data/USDA_Production_Supply_And_Distribution.csv")

In [3]:
# Filtering for only the years 1998 and 2021

USDA9821 <- filter(USDA, Year == 2021 | Year == 1998)

unique(USDA9821$Year)

In [5]:
unique(USDA9821$Commodity_Description)

[1] 1998 2021

 [1] "Almonds, Shelled Basis"        "Animal Numbers, Cattle"
 [3] "Animal Numbers, Swine"         "Apple Juice, Concentrated"
 [5] "Apples, Fresh"                 "Asparagus, Fresh"
 [7] "Avocados, Fresh"               "Barley"
 [9] "Citrus, Other, Fresh"          "Coffee, Green"
[11] "Corn"                          "Cotton"
[13] "Dairy, Butter"                 "Dairy, Cheese"
[15] "Dairy, Dry Whole Milk Powder"  "Dairy, Milk, Fluid"
[17] "Dairy, Milk, Nonfat Dry"       "Filberts, Inshell Basis"
[19] "Fresh Apricots"                "Fresh Cherries,(Sweet&Sour)"
[21] "Fresh Peaches & Nectarines"    "Fresh Plums & Prunes"
[23] "Grapefruit Juice"              "Grapefruit, Fresh"
[25] "Grapes, Table, Fresh"          "Kiwifruit"
[27] "Lemon Juice"                   "Lemons, Fresh"
[29] "Macadamia, Inshell Basis"      "Meal, Copra"
[31] "Meal, Cottonseed"              "Meal, Fish"
[33] "Meal, Palm Kernel"             "Meal, Peanut"
[35] "Meal, Rapeseed"                "Meal, Soybean"
[37] "Meal, Soybean (Local)"         "Meal, Sunflowerseed"
[39] "Meat, Beef and Veal"           "Meat, Swine"
[41] "Millet"                        "Mixed Grain"
[43] "Oats"                          "Oil, Coconut"
[45] "Oil, Cottonseed"               "Oil, Olive"
[47] "Oil, Palm"                     "Oil, Palm Kernel"
[49] "Oil, Peanut"                   "Oil, Rapeseed"
[51] "Oil, Soybean"                  "Oil, Soybean (Local)"
[53] "Oil, Sunflowerseed"            "Oilseed, Copra"
[55] "Oilseed, Cottonseed"           "Oilseed, Palm Kernel"
[57] "Oilseed, Peanut"               "Oilseed, Rapeseed"
[59] "Oilseed, Soybean"              "Oilseed, Soybean (Local)"
[61] "Oilseed, Sunflowerseed"        "Orange Juice"
[63] "Oranges, Fresh"                "Peaches, Canned"
[65] "Pears, Canned"                 "Pears, Fresh"
[67] "Pecans, Inshell Basis"         "Pistachios, Inshell Basis"
[69] "Potato Products, Frozen"       "Poultry, Meat, Broiler"
[71] "Poultry, Meat, Turkey"         "Prunes (Plums, Dried)"
[73] "Raisins"                       "Rice, Milled"
[75] "Rye"                           "Sorghum"
[77] "Strawberries, Fresh"           "Strawberries, Frozen"
[79] "Sugar, Centrifugal"            "Tangerine Juice"
[81] "Tangerines, Fresh"             "Tobacco, Mfg., Cigarettes"
[83] "Tobacco, Unmfg., Total"        "Tomato Paste,28-30% TSS Basis"
[85] "Tomato Sauce"                  "Tomatoes, Canned"
[87] "Walnuts, Inshell Basis"        "Wheat"
[89] "Tangerine/Mandarin Juice"      "Tangerines/Mandarins, Fresh"
[91] "Macadamia, Wet -Inshell Basis" "Grapes, Fresh"
[93] "Lemons/Limes, Fresh"           "Grapes"
[95] "Cherries (Sweet&Sour), Fresh"  "Grapes, Fresh Table"
[97] "Peaches & Nectarines, Fresh"   "Meat, Chicken"

In [9]:
# Filtering only highly-correlated commodities to Honey

USDA9821Filtered <- filter(USDA9821, Commodity_Description == 'Almonds, Shelled Basis' |
                           Commodity_Description == 'Apples, Fresh' |
                           Commodity_Description == 'Corn' |
                           Commodity_Description == 'Grapefruit, Fresh' |
                           Commodity_Description == 'Meat, Swine' |
                           Commodity_Description == 'Barley' |
                           Commodity_Description == 'Oats' |
                           Commodity_Description == 'Rye' |
                           Commodity_Description == 'Oil, Soybean' |
                           Commodity_Description == 'Oil, Rapeseed' |
                           Commodity_Description == 'Walnuts, Inshell Basis' |
                           Commodity_Description == 'Coffee, Green' |
                           Commodity_Description == 'Dairy, Milk, Fluid')

unique(USDA9821Filtered$Commodity_Description)

 [1] "Almonds, Shelled Basis" "Apples, Fresh"          "Barley"
 [4] "Coffee, Green"          "Corn"                   "Dairy, Milk, Fluid"
 [7] "Grapefruit, Fresh"      "Meat, Swine"            "Oats"
[10] "Oil, Rapeseed"          "Oil, Soybean"           "Rye"
[13] "Walnuts, Inshell Basis"

In [10]:
# Deleteing null values
USDA9821Filtered <- na.omit(USDA9821Filtered)

In [27]:
USDA9821Filtered <- data.frame(USDA9821Filtered)

USDA9821Filtered1 <- data.frame(USDA9821Filtered)

In [32]:
# Converting all the possible Measurements into common MT (or Metric Ton)


# Convert the 1000 MT to Tons

USDA9821Filtered$Value[USDA9821Filtered$Unit_Description == '(1000 MT)'] <- USDA9821Filtered$Value * 1000
USDA9821Filtered$Unit_Description[USDA9821Filtered$Unit_Description == '(1000 MT)'] <- '(MT)'

# Convert the (1000 60 KG BAGS) to Tons

USDA9821Filtered$Value[USDA9821Filtered$Unit_Description == '(1000 60 KG BAGS)'] <- USDA9821Filtered$Value * 1000 * .001 * 60
USDA9821Filtered$Unit_Description[USDA9821Filtered$Unit_Description == '(1000 60 KG BAGS)'] <- '(MT)'

# Convert the (1000 MT CWE) to Tons

USDA9821Filtered$Value[USDA9821Filtered$Unit_Description == '(1000 MT CWE)'] <- USDA9821Filtered$Value * 1000
USDA9821Filtered$Unit_Description[USDA9821Filtered$Unit_Description == '(1000 MT CWE)'] <- '(MT)'

# Convert the (1000 HA) to Tons

USDA9821Filtered$Value[USDA9821Filtered$Unit_Description == '(1000 HA)'] <- USDA9821Filtered$Value * 1000 * 12.55
USDA9821Filtered$Unit_Description[USDA9821Filtered$Unit_Description == '(1000 HA)'] <- '(MT)'

# Convert the (1000 MT CWE) to Tons

USDA9821Filtered$Value[USDA9821Filtered$Unit_Description == '(MT/HA)'] <- USDA9821Filtered$Value * 12.55
USDA9821Filtered$Unit_Description[USDA9821Filtered$Unit_Description == '(MT/HA)'] <- '(MT)'

# Convert the (KG) to Tons

USDA9821Filtered$Value[USDA9821Filtered$Unit_Description == '(KG)'] <- USDA9821Filtered$Value * 1000 * .001
USDA9821Filtered$Unit_Description[USDA9821Filtered$Unit_Description == '(KG)'] <- '(MT)'


View(USDA9821Filtered)

Warning message in USDA9821Filtered$Value[USDA9821Filtered$Unit_Description == "(KG)"] <- USDA9821Filtered$Value * :
“number of items to replace is not a multiple of replacement length”

      X       Commodity_Description  Country_Code Country_Name   Year
1      120    Almonds, Shelled Basis GR           Greece         1998
2      121    Almonds, Shelled Basis GR           Greece         1998
3      122    Almonds, Shelled Basis GR           Greece         1998
4      123    Almonds, Shelled Basis GR           Greece         1998
5      124    Almonds, Shelled Basis GR           Greece         1998
6      125    Almonds, Shelled Basis GR           Greece         1998
7      126    Almonds, Shelled Basis GR           Greece         1998
8      127    Almonds, Shelled Basis GR           Greece         1998
9      704    Almonds, Shelled Basis IT           Italy          1998
10     705    Almonds, Shelled Basis IT           Italy          1998
11     706    Almonds, Shelled Basis IT           Italy          1998
12     707    Almonds, Shelled Basis IT           Italy          1998
13     708    Almonds, Shelled Basis IT           Italy          1998
14     709    Almonds, Shelled Basis IT           Italy          1998
15     710    Almonds, Shelled Basis IT           Italy          1998
16     711    Almonds, Shelled Basis IT           Italy          1998
17    1072    Almonds, Shelled Basis MO           Morocco        1998
18    1073    Almonds, Shelled Basis MO           Morocco        1998
19    1074    Almonds, Shelled Basis MO           Morocco        1998
20    1075    Almonds, Shelled Basis MO           Morocco        1998
21    1076    Almonds, Shelled Basis MO           Morocco        1998
22    1077    Almonds, Shelled Basis MO           Morocco        1998
23    1078    Almonds, Shelled Basis MO           Morocco        1998
24    1079    Almonds, Shelled Basis MO           Morocco        1998
25    1632    Almonds, Shelled Basis SP           Spain          1998
26    1633    Almonds, Shelled Basis SP           Spain          1998
27    1634    Almonds, Shelled Basis SP           Spain          1998
28    1635    Almonds, Shelled Basis SP           Spain          1998
29    1636    Almonds, Shelled Basis SP           Spain          1998
30    1637    Almonds, Shelled Basis SP           Spain          1998
⋮     ⋮       ⋮                      ⋮            ⋮              ⋮
79168 1611091 Rye                    UK           United Kingdom 2021
79169 1611092 Rye                    UK           United Kingdom 2021
79170 1611093 Rye                    UK           United Kingdom 2021
79171 1611094 Rye                    UK           United Kingdom 2021
79172 1611095 Rye                    UK           United Kingdom 2021
79173 1611096 Rye                    UK           United Kingdom 2021
79174 1611097 Rye                    UK           United Kingdom 2021
79175 1611098 Rye                    UK           United Kingdom 2021
79176 1611099 Rye                    UK           United Kingdom 2021
79177 1611100 Rye                    UK           United Kingdom 2021
79178 1611101 Rye                    UK           United Kingdom 2021
79179 1611102 Rye                    UK           United Kingdom 2021
79180 1611103 Rye                    UK           United Kingdom 2021
79181 1611104 Rye                    UK           United Kingdom 2021
79182 1611105 Rye                    UK           United Kingdom 2021
79183 1612021 Rye                    US           United States  2021
79184 1612022 Rye                    US           United States  2021
79185 1612023 Rye                    US           United States  2021
79186 1612024 Rye                    US           United States  2021
79187 1612025 Rye                    US           United States  2021
79188 1612026 Rye                    US           United States  2021
79189 1612027 Rye                    US           United States  2021
79190 1612028 Rye                    US           United States  2021
79191 1612029 Rye                    US           United States  2021
79192 1612030 Rye                    US           United States  2021
79193 1612031 Rye                    US           United States  2021
79194 1612032 Rye                    US           United States  2021
79195 1612033 Rye                    US           United States  2021
79196 1612034 Rye                    US           United States  2021
79197 1612035 Rye                    US           United States  2021
      Attribute_Description Unit_Description Value     Seen_On
1     Beginning Stocks      (MT)              4523     199900
2     Domestic Consumption  (MT)             14000     199900
3     Ending Stocks         (MT)              3623     199900
4     Exports               (MT)              1500     199900
5     Imports               (MT)              2600     199900
6     Production            (MT)             12000     199900
7     Total Distribution    (MT)             19123     199900
8     Total Supply          (MT)             19123     199900
9     Beginning Stocks      (MT)              2000     199900
10    Domestic Consumption  (MT)             22593     199900
11    Ending Stocks         (MT)              1000     199900
12    Exports               (MT)              1188     199900
13    Imports               (MT)             13781     199900
14    Production            (MT)              9000     199900
15    Total Distribution    (MT)             24781     199900
16    Total Supply          (MT)             24781     199900
17    Beginning Stocks      (MT)               310     199900
18    Domestic Consumption  (MT)              8200     199900
19    Ending Stocks         (MT)               140     199900
20    Exports               (MT)                 0     199900
21    Imports               (MT)                30     199900
22    Production            (MT)              8000     199900
23    Total Distribution    (MT)              8340     199900
24    Total Supply          (MT)              8340     199900
25    Beginning Stocks      (MT)             14000     199900
26    Domestic Consumption  (MT)             29600     199900
27    Ending Stocks         (MT)                 0     199900
28    Exports               (MT)             40700     199900
29    Imports               (MT)             26300     199900
30    Production            (MT)             30000     199900
⋮     ⋮                     ⋮                ⋮         ⋮
79168 Area Harvested        (MT)                     0 202203
79169 Beginning Stocks      (MT)                 17000 202203
79170 Domestic Consumption  (MT)                300000 202203
79171 Ending Stocks         (MT)                 20000 202203
79172 Exports               (MT)                     0 202203
79173 Feed Dom. Consumption (MT)                250000 202203
79174 FSI Consumption       (MT)                 50000 202203
79175 Imports               (MT)                300000 202203
79176 Production            (MT)                  3000 202203
79177 Total Distribution    (MT)                320000 202203
79178 Total Supply          (MT)                320000 202203
79179 TY Exports            (MT)                     0 202203
79180 TY Imp. from U.S.     (MT)                     0 202203
79181 TY Imports            (MT)                300000 202203
79182 Yield                 (MT)              51204000 202203
79183 Area Harvested        (MT)             677700000 202203
79184 Beginning Stocks      (MT)                   750 202203
79185 Domestic Consumption  (MT)                  1000 202203
79186 Ending Stocks         (MT)               1469000 202203
79187 Exports               (MT)              15850000 202203
79188 Feed Dom. Consumption (MT)               1224000 202203
79189 FSI Consumption       (MT)                     0 202203
79190 Imports               (MT)              12300000 202203
79191 Production            (MT)               3550000 202203
79192 Total Distribution    (MT)              15600000 202203
79193 Total Supply          (MT)                  5000 202203
79194 TY Exports            (MT)              17074000 202203
79195 TY Imp. from U.S.     (MT)              17074000 202203
79196 TY Imports            (MT)                     0 202203
79197 Yield                 (MT)                338850 202203

In [36]:
# Looking at unique Units of Measurements

unique(USDA9821Filtered$Unit_Description)

[1] "(MT)"

In [35]:
# Deleteing the rows for units that can't be converted into MT

USDA9821Filtered <- USDA9821Filtered[USDA9821Filtered$Unit_Description != '(PERCENT)', ] 

USDA9821Filtered <- USDA9821Filtered[USDA9821Filtered$Unit_Description != '(1000 HEAD)', ]

In [41]:
USDA9821Filtered

      X       Commodity_Description  Country_Code Country_Name   Year
1      120    Almonds, Shelled Basis GR           Greece         1998
2      121    Almonds, Shelled Basis GR           Greece         1998
3      122    Almonds, Shelled Basis GR           Greece         1998
4      123    Almonds, Shelled Basis GR           Greece         1998
5      124    Almonds, Shelled Basis GR           Greece         1998
6      125    Almonds, Shelled Basis GR           Greece         1998
7      126    Almonds, Shelled Basis GR           Greece         1998
8      127    Almonds, Shelled Basis GR           Greece         1998
9      704    Almonds, Shelled Basis IT           Italy          1998
10     705    Almonds, Shelled Basis IT           Italy          1998
11     706    Almonds, Shelled Basis IT           Italy          1998
12     707    Almonds, Shelled Basis IT           Italy          1998
13     708    Almonds, Shelled Basis IT           Italy          1998
14     709    Almonds, Shelled Basis IT           Italy          1998
15     710    Almonds, Shelled Basis IT           Italy          1998
16     711    Almonds, Shelled Basis IT           Italy          1998
17    1072    Almonds, Shelled Basis MO           Morocco        1998
18    1073    Almonds, Shelled Basis MO           Morocco        1998
19    1074    Almonds, Shelled Basis MO           Morocco        1998
20    1075    Almonds, Shelled Basis MO           Morocco        1998
21    1076    Almonds, Shelled Basis MO           Morocco        1998
22    1077    Almonds, Shelled Basis MO           Morocco        1998
23    1078    Almonds, Shelled Basis MO           Morocco        1998
24    1079    Almonds, Shelled Basis MO           Morocco        1998
25    1632    Almonds, Shelled Basis SP           Spain          1998
26    1633    Almonds, Shelled Basis SP           Spain          1998
27    1634    Almonds, Shelled Basis SP           Spain          1998
28    1635    Almonds, Shelled Basis SP           Spain          1998
29    1636    Almonds, Shelled Basis SP           Spain          1998
30    1637    Almonds, Shelled Basis SP           Spain          1998
⋮     ⋮       ⋮                      ⋮            ⋮              ⋮
79168 1611091 Rye                    UK           United Kingdom 2021
79169 1611092 Rye                    UK           United Kingdom 2021
79170 1611093 Rye                    UK           United Kingdom 2021
79171 1611094 Rye                    UK           United Kingdom 2021
79172 1611095 Rye                    UK           United Kingdom 2021
79173 1611096 Rye                    UK           United Kingdom 2021
79174 1611097 Rye                    UK           United Kingdom 2021
79175 1611098 Rye                    UK           United Kingdom 2021
79176 1611099 Rye                    UK           United Kingdom 2021
79177 1611100 Rye                    UK           United Kingdom 2021
79178 1611101 Rye                    UK           United Kingdom 2021
79179 1611102 Rye                    UK           United Kingdom 2021
79180 1611103 Rye                    UK           United Kingdom 2021
79181 1611104 Rye                    UK           United Kingdom 2021
79182 1611105 Rye                    UK           United Kingdom 2021
79183 1612021 Rye                    US           United States  2021
79184 1612022 Rye                    US           United States  2021
79185 1612023 Rye                    US           United States  2021
79186 1612024 Rye                    US           United States  2021
79187 1612025 Rye                    US           United States  2021
79188 1612026 Rye                    US           United States  2021
79189 1612027 Rye                    US           United States  2021
79190 1612028 Rye                    US           United States  2021
79191 1612029 Rye                    US           United States  2021
79192 1612030 Rye                    US           United States  2021
79193 1612031 Rye                    US           United States  2021
79194 1612032 Rye                    US           United States  2021
79195 1612033 Rye                    US           United States  2021
79196 1612034 Rye                    US           United States  2021
79197 1612035 Rye                    US           United States  2021
      Attribute_Description Unit_Description Value     Seen_On
1     Beginning Stocks      (MT)              4523     199900
2     Domestic Consumption  (MT)             14000     199900
3     Ending Stocks         (MT)              3623     199900
4     Exports               (MT)              1500     199900
5     Imports               (MT)              2600     199900
6     Production            (MT)             12000     199900
7     Total Distribution    (MT)             19123     199900
8     Total Supply          (MT)             19123     199900
9     Beginning Stocks      (MT)              2000     199900
10    Domestic Consumption  (MT)             22593     199900
11    Ending Stocks         (MT)              1000     199900
12    Exports               (MT)              1188     199900
13    Imports               (MT)             13781     199900
14    Production            (MT)              9000     199900
15    Total Distribution    (MT)             24781     199900
16    Total Supply          (MT)             24781     199900
17    Beginning Stocks      (MT)               310     199900
18    Domestic Consumption  (MT)              8200     199900
19    Ending Stocks         (MT)               140     199900
20    Exports               (MT)                 0     199900
21    Imports               (MT)                30     199900
22    Production            (MT)              8000     199900
23    Total Distribution    (MT)              8340     199900
24    Total Supply          (MT)              8340     199900
25    Beginning Stocks      (MT)             14000     199900
26    Domestic Consumption  (MT)             29600     199900
27    Ending Stocks         (MT)                 0     199900
28    Exports               (MT)             40700     199900
29    Imports               (MT)             26300     199900
30    Production            (MT)             30000     199900
⋮     ⋮                     ⋮                ⋮         ⋮
79168 Area Harvested        (MT)                     0 202203
79169 Beginning Stocks      (MT)                 17000 202203
79170 Domestic Consumption  (MT)                300000 202203
79171 Ending Stocks         (MT)                 20000 202203
79172 Exports               (MT)                     0 202203
79173 Feed Dom. Consumption (MT)                250000 202203
79174 FSI Consumption       (MT)                 50000 202203
79175 Imports               (MT)                300000 202203
79176 Production            (MT)                  3000 202203
79177 Total Distribution    (MT)                320000 202203
79178 Total Supply          (MT)                320000 202203
79179 TY Exports            Exports                  0 202203
79180 TY Imp. from U.S.     (MT)                     0 202203
79181 TY Imports            Imports             300000 202203
79182 Yield                 (MT)              51204000 202203
79183 Area Harvested        (MT)             677700000 202203
79184 Beginning Stocks      (MT)                   750 202203
79185 Domestic Consumption  (MT)                  1000 202203
79186 Ending Stocks         (MT)               1469000 202203
79187 Exports               (MT)              15850000 202203
79188 Feed Dom. Consumption (MT)               1224000 202203
79189 FSI Consumption       (MT)                     0 202203
79190 Imports               (MT)              12300000 202203
79191 Production            (MT)               3550000 202203
79192 Total Distribution    (MT)              15600000 202203
79193 Total Supply          (MT)                  5000 202203
79194 TY Exports            Exports           17074000 202203
79195 TY Imp. from U.S.     (MT)              17074000 202203
79196 TY Imports            Imports                  0 202203
79197 Yield                 (MT)                338850 202203

In [47]:
# Dropping unnecessary values & Merging Attribute Descriptions


# Converting different types of Imports to Imports
# 'Bean Imports', 'Roast & Ground Imports', 'TY Imports, Soluble Imports

# Convert the Bean Imports to Imports

USDA9821Filtered$Attribute_Description[USDA9821Filtered$Attribute_Description == 'Bean Imports'] <- 'Imports'

# Convert the Roast & Ground Imports to Imports

USDA9821Filtered$Attribute_Description[USDA9821Filtered$Attribute_Description == 'Roast & Ground Imports'] <- 'Imports'

# Convert the TY Imports to Imports

USDA9821Filtered$Attribute_Description[USDA9821Filtered$Attribute_Description == 'TY Imports'] <- 'Imports'

# Convert the Soluble Imports to Imports

USDA9821Filtered$Attribute_Description[USDA9821Filtered$Attribute_Description == 'Soluble Imports'] <- 'Imports'


# Converting different types of Exports to Exports
# 'Bean Exports', 'Roast & Ground Exports', 'TY Exports', 'Soluble Exports'


# Convert the Bean Exports to Exports

USDA9821Filtered$Attribute_Description[USDA9821Filtered$Attribute_Description == 'Bean Exports'] <- 'Exports'

# Convert the Roast & Ground Exports to Exports

USDA9821Filtered$Attribute_Description[USDA9821Filtered$Attribute_Description == 'Roast & Ground Exports'] <- 'Exports'

# Convert the TY Exports to Exports

USDA9821Filtered$Attribute_Description[USDA9821Filtered$Attribute_Description == 'TY Exports'] <- 'Exports'

# Convert the Soluble Exports to Exports

USDA9821Filtered$Attribute_Description[USDA9821Filtered$Attribute_Description == 'Soluble Exports'] <- 'Exports'

In [56]:
# Converting different types of Production to Production
# Arabica Production, Cows Milk Production, Non-Comm. Production, Robusta Production, Other Milk Production, Area Harvested

# Convert the Arabica Production to Production

USDA9821Filtered$Attribute_Description[USDA9821Filtered$Attribute_Description == 'Arabica Production'] <- 'Production'


# Convert the Cows Milk Production to Production

USDA9821Filtered$Attribute_Description[USDA9821Filtered$Attribute_Description == 'Cows Milk Production'] <- 'Production'


# Convert the Non-Comm. Production to Production

USDA9821Filtered$Attribute_Description[USDA9821Filtered$Attribute_Description == 'Non-Comm. Production'] <- 'Production'


# Convert the Robusta Production to Production

USDA9821Filtered$Attribute_Description[USDA9821Filtered$Attribute_Description == 'Robusta Production'] <- 'Production'


# Convert the Other Milk Production to Production

USDA9821Filtered$Attribute_Description[USDA9821Filtered$Attribute_Description == 'Other Milk Production'] <- 'Production'


# Convert the Other Area Harvested to Production

USDA9821Filtered$Attribute_Description[USDA9821Filtered$Attribute_Description == 'Area Harvested'] <- 'Production'


# Convert the Other Production to Production

USDA9821Filtered$Attribute_Description[USDA9821Filtered$Attribute_Description == 'Other Production'] <- 'Production'

In [51]:
# Converting different types of Domestic Consumptions to Domestic Consumption
# Soluble Dom. Cons., Rst,Ground Dom. Consum, Fluid Use Dom. Consum., FSI Consumption, Feed Dom. Consumption, 
# Industrial Dom. Cons, Food Use Dom. Cons., Fresh Dom. Consumption, Industrial Dom. Cons.

# Convert the Soluble Dom. Cons. to Domestic Consumption

USDA9821Filtered$Attribute_Description[USDA9821Filtered$Attribute_Description == 'Soluble Dom. Cons.'] <- 'Domestic Consumption'


# Convert the Rst,Ground Dom. Consum. to Domestic Consumption

USDA9821Filtered$Attribute_Description[USDA9821Filtered$Attribute_Description == 'Rst,Ground Dom. Consum'] <- 'Domestic Consumption'


# Convert the Fluid Use Dom. Consum. to Domestic Consumption

USDA9821Filtered$Attribute_Description[USDA9821Filtered$Attribute_Description == 'Fluid Use Dom. Consum.'] <- 'Domestic Consumption'


# Convert the FSI Consumption to Domestic Consumption

USDA9821Filtered$Attribute_Description[USDA9821Filtered$Attribute_Description == 'FSI Consumption'] <- 'Domestic Consumption'


# Convert the Feed Dom. Consumption to Domestic Consumption

USDA9821Filtered$Attribute_Description[USDA9821Filtered$Attribute_Description == 'Feed Dom. Consumption'] <- 'Domestic Consumption'


# Convert the Industrial Dom. Cons to Domestic Consumption

USDA9821Filtered$Attribute_Description[USDA9821Filtered$Attribute_Description == 'Industrial Dom. Cons'] <- 'Domestic Consumption'


# Convert the Food Use Dom. Cons. to Domestic Consumption

USDA9821Filtered$Attribute_Description[USDA9821Filtered$Attribute_Description == 'Food Use Dom. Cons.'] <- 'Domestic Consumption'


# Convert the Fresh Dom. Consumption to Domestic Consumption

USDA9821Filtered$Attribute_Description[USDA9821Filtered$Attribute_Description == 'Fresh Dom. Consumption'] <- 'Domestic Consumption'


# Convert the Industrial Dom. Cons. to Domestic Consumption

USDA9821Filtered$Attribute_Description[USDA9821Filtered$Attribute_Description == 'Industrial Dom. Cons.'] <- 'Domestic Consumption'

In [60]:
# Filtering the data set and keeping only 'Production', 'Imports', 'Exports', 'Domestic Consumption'

USDAFil <- filter(USDA9821Filtered, Attribute_Description == 'Production' |
                           Attribute_Description == 'Imports' |
                           Attribute_Description == 'Exports' |
                           Attribute_Description == 'Domestic Consumption')

unique(USDAFil$Attribute_Description)

USDAFilCopy <- data.frame(USDAFil)

[1] "Domestic Consumption" "Exports"              "Imports"
[4] "Production"

In [62]:
# Removing unnecessary columns

USDAFil <- subset(USDAFil, select = -c(X, Seen_On))
USDAFil

      Commodity_Description  Country_Code Country_Name   Year
1     Almonds, Shelled Basis GR           Greece         1998
2     Almonds, Shelled Basis GR           Greece         1998
3     Almonds, Shelled Basis GR           Greece         1998
4     Almonds, Shelled Basis GR           Greece         1998
5     Almonds, Shelled Basis IT           Italy          1998
6     Almonds, Shelled Basis IT           Italy          1998
7     Almonds, Shelled Basis IT           Italy          1998
8     Almonds, Shelled Basis IT           Italy          1998
9     Almonds, Shelled Basis MO           Morocco        1998
10    Almonds, Shelled Basis MO           Morocco        1998
11    Almonds, Shelled Basis MO           Morocco        1998
12    Almonds, Shelled Basis MO           Morocco        1998
13    Almonds, Shelled Basis SP           Spain          1998
14    Almonds, Shelled Basis SP           Spain          1998
15    Almonds, Shelled Basis SP           Spain          1998
16    Almonds, Shelled Basis SP           Spain          1998
17    Almonds, Shelled Basis TU           Turkey         1998
18    Almonds, Shelled Basis TU           Turkey         1998
19    Almonds, Shelled Basis TU           Turkey         1998
20    Almonds, Shelled Basis TU           Turkey         1998
21    Almonds, Shelled Basis US           United States  1998
22    Almonds, Shelled Basis US           United States  1998
23    Almonds, Shelled Basis US           United States  1998
24    Almonds, Shelled Basis US           United States  1998
25    Apples, Fresh          AR           Argentina      1998
26    Apples, Fresh          AR           Argentina      1998
27    Apples, Fresh          AR           Argentina      1998
28    Apples, Fresh          AR           Argentina      1998
29    Apples, Fresh          AR           Argentina      1998
30    Apples, Fresh          AS           Australia      1998
⋮     ⋮                      ⋮            ⋮              ⋮
45288 Rye                    TU           Turkey         2021
45289 Rye                    TU           Turkey         2021
45290 Rye                    TU           Turkey         2021
45291 Rye                    UP           Ukraine        2021
45292 Rye                    UP           Ukraine        2021
45293 Rye                    UP           Ukraine        2021
45294 Rye                    UP           Ukraine        2021
45295 Rye                    UP           Ukraine        2021
45296 Rye                    UP           Ukraine        2021
45297 Rye                    UP           Ukraine        2021
45298 Rye                    UP           Ukraine        2021
45299 Rye                    UP           Ukraine        2021
45300 Rye                    UK           United Kingdom 2021
45301 Rye                    UK           United Kingdom 2021
45302 Rye                    UK           United Kingdom 2021
45303 Rye                    UK           United Kingdom 2021
45304 Rye                    UK           United Kingdom 2021
45305 Rye                    UK           United Kingdom 2021
45306 Rye                    UK           United Kingdom 2021
45307 Rye                    UK           United Kingdom 2021
45308 Rye                    UK           United Kingdom 2021
45309 Rye                    US           United States  2021
45310 Rye                    US           United States  2021
45311 Rye                    US           United States  2021
45312 Rye                    US           United States  2021
45313 Rye                    US           United States  2021
45314 Rye                    US           United States  2021
45315 Rye                    US           United States  2021
45316 Rye                    US           United States  2021
45317 Rye                    US           United States  2021
      Attribute_Description Unit_Description Value
1     Domestic Consumption  (MT)               14000
2     Exports               (MT)                1500
3     Imports               (MT)                2600
4     Production            (MT)               12000
5     Domestic Consumption  (MT)               22593
6     Exports               (MT)                1188
7     Imports               (MT)               13781
8     Production            (MT)                9000
9     Domestic Consumption  (MT)                8200
10    Exports               (MT)                   0
11    Imports               (MT)                  30
12    Production            (MT)                8000
13    Domestic Consumption  (MT)               29600
14    Exports               (MT)               40700
15    Imports               (MT)               26300
16    Production            (MT)               30000
17    Domestic Consumption  (MT)               13800
18    Exports               (MT)                 200
19    Imports               (MT)                2000
20    Production            (MT)               12000
21    Domestic Consumption  (MT)               88414
22    Exports               (MT)              183917
23    Imports               (MT)                  86
24    Production            (MT)              235884
25    Exports               (MT)              179723
26    Domestic Consumption  (MT)              330172
27    Imports               (MT)               11858
28    Production            (MT)                   0
29    Production            (MT)             1316035
30    Exports               (MT)               26402
⋮     ⋮                     ⋮                ⋮
45288 Production            (MT)                     0
45289 Exports               (MT)                     0
45290 Imports               (MT)               1800000
45291 Production            (MT)                476900
45292 Domestic Consumption  (MT)                 10000
45293 Exports               (MT)                100000
45294 Domestic Consumption  (MT)               1800000
45295 Domestic Consumption  (MT)                     0
45296 Imports               (MT)               1921000
45297 Production            (MT)               1921000
45298 Exports               (MT)               1800000
45299 Imports               (MT)                  4000
45300 Production            (MT)                     0
45301 Domestic Consumption  (MT)                300000
45302 Exports               (MT)                     0
45303 Domestic Consumption  (MT)                250000
45304 Domestic Consumption  (MT)                 50000
45305 Imports               (MT)                300000
45306 Production            (MT)                  3000
45307 Exports               (MT)                     0
45308 Imports               (MT)                300000
45309 Production            (MT)             677700000
45310 Domestic Consumption  (MT)                  1000
45311 Exports               (MT)              15850000
45312 Domestic Consumption  (MT)               1224000
45313 Domestic Consumption  (MT)                     0
45314 Imports               (MT)              12300000
45315 Production            (MT)               3550000
45316 Exports               (MT)              17074000
45317 Imports               (MT)                     0

In [65]:
# Picking the maximum Value for each Commodity since there seems to be many duplicate entries.

Global98_21 = USDAFil %>% group_by(Commodity_Description, Year, Attribute_Description, Country_Code, Country_Name) %>% 
  summarise(Value = max(Value), Unit_Description = "(MT)",
            .groups = 'drop')

# Deleting the Records where Value = 0

Global98_21 <- Global98_21[Global98_21$Value != 0, ] 

# Recoding from tibble to dataframe

Global1998and2021 <- as.data.frame(Global98_21)

View(Global1998and2021)

     Commodity_Description  Year Attribute_Description Country_Code
1    Almonds, Shelled Basis 1998 Domestic Consumption  GR
2    Almonds, Shelled Basis 1998 Domestic Consumption  IT
3    Almonds, Shelled Basis 1998 Domestic Consumption  MO
4    Almonds, Shelled Basis 1998 Domestic Consumption  SP
5    Almonds, Shelled Basis 1998 Domestic Consumption  TU
6    Almonds, Shelled Basis 1998 Domestic Consumption  US
7    Almonds, Shelled Basis 1998 Exports               GR
8    Almonds, Shelled Basis 1998 Exports               IT
9    Almonds, Shelled Basis 1998 Exports               SP
10   Almonds, Shelled Basis 1998 Exports               TU
11   Almonds, Shelled Basis 1998 Exports               US
12   Almonds, Shelled Basis 1998 Imports               GR
13   Almonds, Shelled Basis 1998 Imports               IT
14   Almonds, Shelled Basis 1998 Imports               MO
15   Almonds, Shelled Basis 1998 Imports               SP
16   Almonds, Shelled Basis 1998 Imports               TU
17   Almonds, Shelled Basis 1998 Imports               US
18   Almonds, Shelled Basis 1998 Production            GR
19   Almonds, Shelled Basis 1998 Production            IT
20   Almonds, Shelled Basis 1998 Production            MO
21   Almonds, Shelled Basis 1998 Production            SP
22   Almonds, Shelled Basis 1998 Production            TU
23   Almonds, Shelled Basis 1998 Production            US
24   Almonds, Shelled Basis 2021 Domestic Consumption  AG
25   Almonds, Shelled Basis 2021 Domestic Consumption  AR
26   Almonds, Shelled Basis 2021 Domestic Consumption  AS
27   Almonds, Shelled Basis 2021 Domestic Consumption  BO
28   Almonds, Shelled Basis 2021 Domestic Consumption  BR
29   Almonds, Shelled Basis 2021 Domestic Consumption  CA
30   Almonds, Shelled Basis 2021 Domestic Consumption  CH
⋮    ⋮                      ⋮    ⋮                     ⋮
4916 Walnuts, Inshell Basis 2021 Imports               IZ
4917 Walnuts, Inshell Basis 2021 Imports               JA
4918 Walnuts, Inshell Basis 2021 Imports               KG
4919 Walnuts, Inshell Basis 2021 Imports               KS
4920 Walnuts, Inshell Basis 2021 Imports               KZ
4921 Walnuts, Inshell Basis 2021 Imports               LE
4922 Walnuts, Inshell Basis 2021 Imports               MD
4923 Walnuts, Inshell Basis 2021 Imports               MO
4924 Walnuts, Inshell Basis 2021 Imports               MX
4925 Walnuts, Inshell Basis 2021 Imports               NO
4926 Walnuts, Inshell Basis 2021 Imports               PK
4927 Walnuts, Inshell Basis 2021 Imports               RS
4928 Walnuts, Inshell Basis 2021 Imports               SY
4929 Walnuts, Inshell Basis 2021 Imports               SZ
4930 Walnuts, Inshell Basis 2021 Imports               TC
4931 Walnuts, Inshell Basis 2021 Imports               TU
4932 Walnuts, Inshell Basis 2021 Imports               TW
4933 Walnuts, Inshell Basis 2021 Imports               UK
4934 Walnuts, Inshell Basis 2021 Imports               UP
4935 Walnuts, Inshell Basis 2021 Imports               US
4936 Walnuts, Inshell Basis 2021 Production            AS
4937 Walnuts, Inshell Basis 2021 Production            BR
4938 Walnuts, Inshell Basis 2021 Production            CH
4939 Walnuts, Inshell Basis 2021 Production            CI
4940 Walnuts, Inshell Basis 2021 Production            E4
4941 Walnuts, Inshell Basis 2021 Production            IN
4942 Walnuts, Inshell Basis 2021 Production            MD
4943 Walnuts, Inshell Basis 2021 Production            TU
4944 Walnuts, Inshell Basis 2021 Production            UP
4945 Walnuts, Inshell Basis 2021 Production            US
     Country_Name         Value   Unit_Description
1    Greece                14000  (MT)
2    Italy                 22593  (MT)
3    Morocco                8200  (MT)
4    Spain                 29600  (MT)
5    Turkey                13800  (MT)
6    United States         88414  (MT)
7    Greece                 1500  (MT)
8    Italy                  1188  (MT)
9    Spain                 40700  (MT)
10   Turkey                  200  (MT)
11   United States        183917  (MT)
12   Greece                 2600  (MT)
13   Italy                 13781  (MT)
14   Morocco                  30  (MT)
15   Spain                 26300  (MT)
16   Turkey                 2000  (MT)
17   United States            86  (MT)
18   Greece                12000  (MT)
19   Italy                  9000  (MT)
20   Morocco                8000  (MT)
21   Spain                 30000  (MT)
22   Turkey                12000  (MT)
23   United States        235884  (MT)
24   Algeria                5000  (MT)
25   Argentina              4000  (MT)
26   Australia             46000  (MT)
27   Belarus                3000  (MT)
28   Brazil                 5000  (MT)
29   Canada                33000  (MT)
30   China                165000  (MT)
⋮    ⋮                    ⋮       ⋮
4916 Iraq                   15000 (MT)
4917 Japan                  45000 (MT)
4918 Kyrgyzstan             25000 (MT)
4919 Korea, South           40000 (MT)
4920 Kazakhstan             60000 (MT)
4921 Lebanon                 7000 (MT)
4922 Moldova                 6000 (MT)
4923 Morocco                20000 (MT)
4924 Mexico                 10000 (MT)
4925 Norway                  3500 (MT)
4926 Pakistan               20000 (MT)
4927 Russia                 25000 (MT)
4928 Syria                   4500 (MT)
4929 Switzerland             8000 (MT)
4930 United Arab Emirates   65000 (MT)
4931 Turkey                 94000 (MT)
4932 Taiwan                 14000 (MT)
4933 United Kingdom         27000 (MT)
4934 Ukraine                   25 (MT)
4935 United States           3000 (MT)
4936 Australia              13000 (MT)
4937 Brazil                 10000 (MT)
4938 China                1100000 (MT)
4939 Chile                 152000 (MT)
4940 European Union        126601 (MT)
4941 India                  36000 (MT)
4942 Moldova                21000 (MT)
4943 Turkey                 68000 (MT)
4944 Ukraine               132745 (MT)
4945 United States         607814 (MT)

In [67]:
# Writing the CSV file

write_csv(Global1998and2021, "../Data/Global1998and2021.csv")