In [11]:
# Load Packages

library(readr)
library(dplyr)
library(ggplot2)

In [12]:
# Load Data

# Reading honeyproduction CSV file

honeyproduction <- read_csv("../Data/honeyproduction.csv")

Rows: 626 Columns: 8

── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (1): state
dbl (7): numcol, yieldpercol, totalprod, stocks, priceperlb, prodvalue, year


ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [13]:
# Assigning to a new dataset 
honeyproductionDS <- honeyproduction

In [14]:
# Data Wrangling 

# Recoding into a New Variable State_Name based on state 
# First define a new Variable

honeyproductionDS$State_Name <- NA

In [15]:
# State Code to State Names

honeyproductionDS$State_Name[honeyproductionDS$state == 'AK'] <- 'Alaska'
honeyproductionDS$State_Name[honeyproductionDS$state == 'AL'] <- 'Alabama'
honeyproductionDS$State_Name[honeyproductionDS$state == 'AR'] <- 'Arkansas'
honeyproductionDS$State_Name[honeyproductionDS$state == 'AZ'] <- 'Arizona'
honeyproductionDS$State_Name[honeyproductionDS$state == 'CA'] <- 'California'
honeyproductionDS$State_Name[honeyproductionDS$state == 'CO'] <- 'Colorado'
honeyproductionDS$State_Name[honeyproductionDS$state == 'CT'] <- 'Connecticut'
honeyproductionDS$State_Name[honeyproductionDS$state == 'DC'] <- 'District of Columbia'

honeyproductionDS$State_Name[honeyproductionDS$state == 'DE'] <- 'Delaware'
honeyproductionDS$State_Name[honeyproductionDS$state == 'FL'] <- 'Florida'
honeyproductionDS$State_Name[honeyproductionDS$state == 'GA'] <- 'Georgia'
honeyproductionDS$State_Name[honeyproductionDS$state == 'HI'] <-  'Hawaii'
honeyproductionDS$State_Name[honeyproductionDS$state == 'IA'] <-  'Iowa'
honeyproductionDS$State_Name[honeyproductionDS$state == 'ID'] <-  'Idaho'
honeyproductionDS$State_Name[honeyproductionDS$state == 'IL'] <-  'Illinois'
honeyproductionDS$State_Name[honeyproductionDS$state == 'IN'] <-  'Indiana'

honeyproductionDS$State_Name[honeyproductionDS$state == 'KS'] <-  'Kansas'
honeyproductionDS$State_Name[honeyproductionDS$state == 'KY'] <-  'Kentucky'
honeyproductionDS$State_Name[honeyproductionDS$state == 'LA'] <-  'Louisiana'
honeyproductionDS$State_Name[honeyproductionDS$state == 'MA'] <-  'Massachusetts'
honeyproductionDS$State_Name[honeyproductionDS$state == 'MD'] <-  'Maryland'
honeyproductionDS$State_Name[honeyproductionDS$state == 'ME'] <-  'Maine'
honeyproductionDS$State_Name[honeyproductionDS$state == 'MI'] <-  'Michigan'
honeyproductionDS$State_Name[honeyproductionDS$state == 'MN'] <-  'Minnesota'

honeyproductionDS$State_Name[honeyproductionDS$state == 'MO'] <-  'Missouri'
honeyproductionDS$State_Name[honeyproductionDS$state == 'MS'] <-  'Mississippi'
honeyproductionDS$State_Name[honeyproductionDS$state == 'MT'] <-  'Montana'
honeyproductionDS$State_Name[honeyproductionDS$state == 'NC'] <-  'North Carolina'
honeyproductionDS$State_Name[honeyproductionDS$state == 'ND'] <-  'North Dakota'
honeyproductionDS$State_Name[honeyproductionDS$state == 'NE'] <-  'Nebraska'
honeyproductionDS$State_Name[honeyproductionDS$state == 'NH'] <-  'New Hampshire'
honeyproductionDS$State_Name[honeyproductionDS$state == 'NJ'] <-  'New Jersey'
honeyproductionDS$State_Name[honeyproductionDS$state == 'NM'] <-  'New Mexico'
honeyproductionDS$State_Name[honeyproductionDS$state == 'NV'] <-  'Nevada'
honeyproductionDS$State_Name[honeyproductionDS$state == 'NY'] <-  'New York'
honeyproductionDS$State_Name[honeyproductionDS$state == 'OH'] <-  'Ohio'
honeyproductionDS$State_Name[honeyproductionDS$state == 'OK'] <-  'Oklahoma'
honeyproductionDS$State_Name[honeyproductionDS$state == 'OR'] <-  'Oregon'
honeyproductionDS$State_Name[honeyproductionDS$state == 'PA'] <-  'Pennsylvania'
honeyproductionDS$State_Name[honeyproductionDS$state == 'PR'] <-  'Puerto Rico'

honeyproductionDS$State_Name[honeyproductionDS$state == 'RI'] <-  'Rhode Island'
honeyproductionDS$State_Name[honeyproductionDS$state == 'SC'] <-  'South Carolina'
honeyproductionDS$State_Name[honeyproductionDS$state == 'SD'] <-  'South Dakota'
honeyproductionDS$State_Name[honeyproductionDS$state == 'TN'] <-  'Tennessee'
honeyproductionDS$State_Name[honeyproductionDS$state == 'TX'] <-  'Texas'
honeyproductionDS$State_Name[honeyproductionDS$state == 'UT'] <-  'Utah'
honeyproductionDS$State_Name[honeyproductionDS$state == 'VA'] <-  'Virginia'
honeyproductionDS$State_Name[honeyproductionDS$state == 'VT'] <-  'Vermont'
honeyproductionDS$State_Name[honeyproductionDS$state == 'WA'] <- 'Washington'
honeyproductionDS$State_Name[honeyproductionDS$state == 'WI'] <- 'Wisconsin'
honeyproductionDS$State_Name[honeyproductionDS$state == 'WV'] <- 'West Virginia'
honeyproductionDS$State_Name[honeyproductionDS$state == 'WY'] <- 'Wyoming'

View(honeyproductionDS)

    state numcol yieldpercol totalprod stocks   priceperlb prodvalue year
1   AL     16000  71          1136000    159000 0.72         818000  1998
2   AZ     55000  60          3300000   1485000 0.64        2112000  1998
3   AR     53000  65          3445000   1688000 0.59        2033000  1998
4   CA    450000  83         37350000  12326000 0.62       23157000  1998
5   CO     27000  72          1944000   1594000 0.70        1361000  1998
6   FL    230000  98         22540000   4508000 0.64       14426000  1998
7   GA     75000  56          4200000    307000 0.69        2898000  1998
8   HI      8000 118           944000     66000 0.77         727000  1998
9   ID    120000  50          6000000   2220000 0.65        3900000  1998
10  IL      9000  71           639000    204000 1.19         760000  1998
11  IN      9000  92           828000    489000 0.85         704000  1998
12  IA     50000  78          3900000   2301000 0.70        2730000  1998
13  KS     16000  46           736000    390000 0.87         640000  1998
14  KY      3000  50           150000     51000 1.40         210000  1998
15  LA     41000 111          4551000    865000 0.59        2685000  1998
16  ME     10000  26           260000    117000 0.69         179000  1998
17  MD      7000  44           308000     92000 1.10         339000  1998
18  MI     80000  85          6800000   3672000 0.66        4488000  1998
19  MN    140000  79         11060000   2765000 0.65        7189000  1998
20  MS     18000  86          1548000    898000 0.58         898000  1998
21  MO     23000  66          1518000    455000 0.76        1154000  1998
22  MT    115000 122         14030000   5472000 0.64        8979000  1998
23  NE     64000  70          4480000   2240000 0.86        3853000  1998
24  NV     10000  46           460000    175000 1.65         759000  1998
25  NJ     11000  49           539000    167000 0.76         410000  1998
26  NM     14000  55           770000    470000 0.76         585000  1998
27  NY     65000  80          5200000   2444000 0.70        3640000  1998
28  NC      8000  59           472000    151000 1.38         651000  1998
29  ND    230000 128         29440000   8832000 0.63       18547000  1998
30  OH     18000  78          1404000    702000 0.83        1165000  1998
⋮   ⋮     ⋮      ⋮           ⋮         ⋮        ⋮          ⋮         ⋮
597 IN      8000  59           472000   203000  2.54        1199000  2012
598 IA     37000  61          2257000  1196000  2.17        4898000  2012
599 KS      6000  55           330000   125000  2.28         752000  2012
600 KY      5000  51           255000    41000  3.15         803000  2012
601 LA     41000  86          3526000   141000  1.83        6453000  2012
602 ME      4000  34           136000    24000  2.39         325000  2012
603 MI     73000  57          4161000  1332000  2.03        8447000  2012
604 MN    125000  67          8375000  1591000  1.92       16080000  2012
605 MS     18000 118          2124000    64000  1.77        3759000  2012
606 MO      7000  53           371000   108000  2.80        1039000  2012
607 MT    145000  52          7540000  2413000  1.95       14703000  2012
608 NE     43000  65          2795000  1146000  1.93        5394000  2012
609 NJ     14000  33           462000    51000  1.97         910000  2012
610 NM      5000  52           260000    99000  3.39         881000  2012
611 NY     51000  51          2601000   988000  2.23        5800000  2012
612 NC     13000  39           507000   106000  3.76        1906000  2012
613 ND    480000  69         33120000  5962000  1.92       63590000  2012
614 OH     18000  60          1080000   410000  2.46        2657000  2012
615 OR     60000  32          1920000   845000  2.16        4147000  2012
616 PA     16000  60           960000   269000  2.57        2467000  2012
617 SD    260000  63         16380000  3604000  1.95       31941000  2012
618 TN      6000  61           366000    59000  2.93        1072000  2012
619 TX     92000  52          4784000   718000  2.00        9568000  2012
620 UT     25000  38           950000   209000  1.87        1777000  2012
621 VT      4000  60           240000    53000  2.39         574000  2012
622 VA      4000  41           164000    23000  3.77         618000  2012
623 WA     62000  41          2542000  1017000  2.38        6050000  2012
624 WV      6000  48           288000    95000  2.91         838000  2012
625 WI     60000  69          4140000  1863000  2.05        8487000  2012
626 WY     50000  51          2550000   459000  1.87        4769000  2012
    State_Name
1   Alabama
2   Arizona
3   Arkansas
4   California
5   Colorado
6   Florida
7   Georgia
8   Hawaii
9   Idaho
10  Illinois
11  Indiana
12  Iowa
13  Kansas
14  Kentucky
15  Louisiana
16  Maine
17  Maryland
18  Michigan
19  Minnesota
20  Mississippi
21  Missouri
22  Montana
23  Nebraska
24  Nevada
25  New Jersey
26  New Mexico
27  New York
28  North Carolina
29  North Dakota
30  Ohio
⋮   ⋮
597 Indiana
598 Iowa
599 Kansas
600 Kentucky
601 Louisiana
602 Maine
603 Michigan
604 Minnesota
605 Mississippi
606 Missouri
607 Montana
608 Nebraska
609 New Jersey
610 New Mexico
611 New York
612 North Carolina
613 North Dakota
614 Ohio
615 Oregon
616 Pennsylvania
617 South Dakota
618 Tennessee
619 Texas
620 Utah
621 Vermont
622 Virginia
623 Washington
624 West Virginia
625 Wisconsin
626 Wyoming

In [16]:
# Renaming Column names for easy understanding

Honey_Production_DS <- honeyproductionDS %>% 
  rename(
    State_Code = state,
    Num_of_Colony = numcol,
    Production_per_Colony = yieldpercol,
    Total_Production = totalprod,
    Stock_Held = stocks,
    Price_per_Pound = priceperlb,
    Total_Production_Value = prodvalue,
    Year = year
  )

In [17]:
View(Honey_Production_DS)

    State_Code Num_of_Colony Production_per_Colony Total_Production Stock_Held
1   AL          16000         71                    1136000           159000
2   AZ          55000         60                    3300000          1485000
3   AR          53000         65                    3445000          1688000
4   CA         450000         83                   37350000         12326000
5   CO          27000         72                    1944000          1594000
6   FL         230000         98                   22540000          4508000
7   GA          75000         56                    4200000           307000
8   HI           8000        118                     944000            66000
9   ID         120000         50                    6000000          2220000
10  IL           9000         71                     639000           204000
11  IN           9000         92                     828000           489000
12  IA          50000         78                    3900000          2301000
13  KS          16000         46                     736000           390000
14  KY           3000         50                     150000            51000
15  LA          41000        111                    4551000           865000
16  ME          10000         26                     260000           117000
17  MD           7000         44                     308000            92000
18  MI          80000         85                    6800000          3672000
19  MN         140000         79                   11060000          2765000
20  MS          18000         86                    1548000           898000
21  MO          23000         66                    1518000           455000
22  MT         115000        122                   14030000          5472000
23  NE          64000         70                    4480000          2240000
24  NV          10000         46                     460000           175000
25  NJ          11000         49                     539000           167000
26  NM          14000         55                     770000           470000
27  NY          65000         80                    5200000          2444000
28  NC           8000         59                     472000           151000
29  ND         230000        128                   29440000          8832000
30  OH          18000         78                    1404000           702000
⋮   ⋮          ⋮             ⋮                     ⋮                ⋮
597 IN           8000         59                     472000          203000
598 IA          37000         61                    2257000         1196000
599 KS           6000         55                     330000          125000
600 KY           5000         51                     255000           41000
601 LA          41000         86                    3526000          141000
602 ME           4000         34                     136000           24000
603 MI          73000         57                    4161000         1332000
604 MN         125000         67                    8375000         1591000
605 MS          18000        118                    2124000           64000
606 MO           7000         53                     371000          108000
607 MT         145000         52                    7540000         2413000
608 NE          43000         65                    2795000         1146000
609 NJ          14000         33                     462000           51000
610 NM           5000         52                     260000           99000
611 NY          51000         51                    2601000          988000
612 NC          13000         39                     507000          106000
613 ND         480000         69                   33120000         5962000
614 OH          18000         60                    1080000          410000
615 OR          60000         32                    1920000          845000
616 PA          16000         60                     960000          269000
617 SD         260000         63                   16380000         3604000
618 TN           6000         61                     366000           59000
619 TX          92000         52                    4784000          718000
620 UT          25000         38                     950000          209000
621 VT           4000         60                     240000           53000
622 VA           4000         41                     164000           23000
623 WA          62000         41                    2542000         1017000
624 WV           6000         48                     288000           95000
625 WI          60000         69                    4140000         1863000
626 WY          50000         51                    2550000          459000
    Price_per_Pound Total_Production_Value Year State_Name
1   0.72              818000               1998 Alabama
2   0.64             2112000               1998 Arizona
3   0.59             2033000               1998 Arkansas
4   0.62            23157000               1998 California
5   0.70             1361000               1998 Colorado
6   0.64            14426000               1998 Florida
7   0.69             2898000               1998 Georgia
8   0.77              727000               1998 Hawaii
9   0.65             3900000               1998 Idaho
10  1.19              760000               1998 Illinois
11  0.85              704000               1998 Indiana
12  0.70             2730000               1998 Iowa
13  0.87              640000               1998 Kansas
14  1.40              210000               1998 Kentucky
15  0.59             2685000               1998 Louisiana
16  0.69              179000               1998 Maine
17  1.10              339000               1998 Maryland
18  0.66             4488000               1998 Michigan
19  0.65             7189000               1998 Minnesota
20  0.58              898000               1998 Mississippi
21  0.76             1154000               1998 Missouri
22  0.64             8979000               1998 Montana
23  0.86             3853000               1998 Nebraska
24  1.65              759000               1998 Nevada
25  0.76              410000               1998 New Jersey
26  0.76              585000               1998 New Mexico
27  0.70             3640000               1998 New York
28  1.38              651000               1998 North Carolina
29  0.63            18547000               1998 North Dakota
30  0.83             1165000               1998 Ohio
⋮   ⋮               ⋮                      ⋮    ⋮
597 2.54             1199000               2012 Indiana
598 2.17             4898000               2012 Iowa
599 2.28              752000               2012 Kansas
600 3.15              803000               2012 Kentucky
601 1.83             6453000               2012 Louisiana
602 2.39              325000               2012 Maine
603 2.03             8447000               2012 Michigan
604 1.92            16080000               2012 Minnesota
605 1.77             3759000               2012 Mississippi
606 2.80             1039000               2012 Missouri
607 1.95            14703000               2012 Montana
608 1.93             5394000               2012 Nebraska
609 1.97              910000               2012 New Jersey
610 3.39              881000               2012 New Mexico
611 2.23             5800000               2012 New York
612 3.76             1906000               2012 North Carolina
613 1.92            63590000               2012 North Dakota
614 2.46             2657000               2012 Ohio
615 2.16             4147000               2012 Oregon
616 2.57             2467000               2012 Pennsylvania
617 1.95            31941000               2012 South Dakota
618 2.93             1072000               2012 Tennessee
619 2.00             9568000               2012 Texas
620 1.87             1777000               2012 Utah
621 2.39              574000               2012 Vermont
622 3.77              618000               2012 Virginia
623 2.38             6050000               2012 Washington
624 2.91              838000               2012 West Virginia
625 2.05             8487000               2012 Wisconsin
626 1.87             4769000               2012 Wyoming